// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{ type: "autogenerated", dirName: "." }],

  docsSidebar: [
    { type: "doc", id: "introduction", label: "🔖 Introduction" },
    { type: "doc", id: "core-concepts", label: "🧰 Core Concepts" },

    {
      type: "html",
      value: "Get Started: Connect Data",
      className: "sidebar-title",
    },
    {
      type: "category",
      label: "Process Batch Data",
      link: { type: "doc", id: "processing-batch-data" },
      items: [
        "aws-s3-bucket",
        "gcs-bucket",
        "google-bigquery",
        "azure-storage-container",
        "tutorial-druid-ingestion",
        "ingesting-from-big-query",
      ],
    },
    {
      type: "category",
      label: "Process Streaming Data",
      link: { type: "doc", id: "process-streaming-data" },
      items: ["connecting-with-kafka", "tutorial-kafka-ingestion"],
    },
    { type: "doc", id: "metadata-lookups", label: "Metadata Lookups" },
    {
      type: "doc",
      id: "data-ingestion-best-practices-1",
      label: "Ingestion Best Practices",
    },

    {
      type: "html",
      value: "Analyze: Explore Dashboards",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "getting-access-to-rill-dashboards",
      label: "Welcome to Rill Explore",
    },
    {
      type: "category",
      label: "👋 Explore Quickstart",
      link: { type: "doc", id: "getting-started" },
      items: [
        "alerting",
        "scheduled-exports",
        "bookmarking",
        "facet-pivot-table-splits",
      ],
    },
    {
      type: "category",
      label: "🔐 Explore Admin",
      link: { type: "doc", id: "explore-admin" },
      items: [
        "adding-users",
        "admin-security",
        "create-an-external-dashboard",
        "explore-json-examples",
      ],
    },
    { type: "doc", id: "embedding-explore", label: "⚙️ Embedding Explore" },

    {
      type: "html",
      value: "INTEGRATE: 3RD PARTY APPLICATIONS",
      className: "sidebar-title",
    },
    {
      type: "category",
      label: "🔓 Authenticate & Connect",
      link: { type: "doc", id: "authenticating-integrated-applications" },
      items: [
        "api-password",
        "service-accounts",
        "api-access",
        "jdbc-connection",
      ],
    },
    { type: "doc", id: "jupyter", label: "Jupyter" },
    { type: "doc", id: "looker", label: "Looker" },
    { type: "doc", id: "superset", label: "Superset" },
    { type: "doc", id: "tableau", label: "Tableau" },

    { type: "html", value: "Security", className: "sidebar-title" },
    { type: "doc", id: "aws-private-link", label: "Private Link" },
    { type: "doc", id: "aws-encryption", label: "AWS Encryption" },

    { type: "html", value: "Additional Resources", className: "sidebar-title" },
    { type: "doc", id: "faq", label: "❓ FAQ" },
    {
      type: "link",
      label: "🎛 Service Status",
      href: "https://rilldata.statuspage.io/",
    },
    { type: "doc", id: "contact-support", label: "🤓 Contact Support" },
  ],
};

module.exports = sidebars;
