package pgwire

import (
	"context"
	"net"
	"strconv"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rilldata/rill/runtime"
	base "github.com/rilldata/rill/runtime/pkg/pgwire"
	"github.com/rilldata/rill/runtime/testruntime"
	"github.com/stretchr/testify/require"

	_ "github.com/rilldata/rill/runtime/resolvers"
)

func TestInterpolateParameters(t *testing.T) {
	types := pgtype.NewMap()
	binaryInt, err := types.Encode(pgtype.Int4OID, pgtype.BinaryFormatCode, int32(42), nil)
	require.NoError(t, err)
	query, err := interpolateParameters(
		`SELECT value FROM metrics WHERE id = $1 AND label = $2 AND literal = '$1'`,
		[]base.Parameter{
			{OID: pgtype.Int4OID, Format: pgtype.BinaryFormatCode, Value: binaryInt},
			{OID: pgtype.TextOID, Format: pgtype.TextFormatCode, Value: []byte("O'Reilly")},
		},
		types,
	)
	require.NoError(t, err)
	require.Equal(t, `SELECT value FROM metrics WHERE id = 42 AND label = 'O''Reilly'::text AND literal = '$1'`, query)
}

func TestEncodeTimestamptzTextUsesNumericOffset(t *testing.T) {
	value, err := normalizeValue("2022-01-01T00:00:00Z", pgtype.TimestamptzOID)
	require.NoError(t, err)
	encoded, err := encodeValue(pgtype.NewMap(), pgtype.TimestamptzOID, pgtype.TextFormatCode, value)
	require.NoError(t, err)
	require.Equal(t, "2022-01-01 00:00:00+00:00", string(encoded))
}

func TestNormalizeNumericForBinaryEncoding(t *testing.T) {
	value, err := normalizeValue("123.45", pgtype.NumericOID)
	require.NoError(t, err)
	_, err = pgtype.NewMap().Encode(pgtype.NumericOID, pgtype.BinaryFormatCode, value, nil)
	require.NoError(t, err)
}

func TestInferParameterOIDs(t *testing.T) {
	require.Equal(t,
		[]uint32{pgtype.Int4OID, pgtype.TimestamptzOID, pgtype.TextOID},
		inferParameterOIDs("SELECT $1::int4, $2::timestamp with time zone, $3", nil),
	)
}

func TestCatalogClassification(t *testing.T) {
	require.True(t, isCatalogQuery("SHOW timezone"))
	require.True(t, isCatalogQuery("SELECT version()"))
	require.True(t, isCatalogQuery("SELECT * FROM pg_catalog.pg_type"))
	require.False(t, isCatalogQuery("SELECT country FROM sales"))
}

func TestRuntimePGWireSupersetQueriesEndToEnd(t *testing.T) {
	rt, instanceID := testruntime.NewInstanceForProject(t, "ad_bids")
	server, err := base.NewServer(base.Options{
		NewSession: func(context.Context, map[string]string, string) (base.Session, error) {
			return NewSession(rt, instanceID, &runtime.SecurityClaims{Permissions: runtime.AllPermissions, SkipChecks: true})
		},
	})
	require.NoError(t, err)
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	serveCtx, stopServer := context.WithCancel(t.Context())
	serveDone := make(chan error, 1)
	go func() {
		serveDone <- server.Serve(serveCtx, listener)
	}()
	t.Cleanup(func() {
		stopServer()
		require.NoError(t, <-serveDone)
	})

	config, err := pgx.ParseConfig("postgresql://rill@" + listener.Addr().String() + "/default?sslmode=disable")
	require.NoError(t, err)
	conn, err := pgx.ConnectConfig(t.Context(), config)
	require.NoError(t, err)
	defer conn.Close(t.Context())

	// SQLAlchemy resolves the table OID and columns in separate queries. This
	// exercises separate catalog rebuilds through the actual extended protocol.
	var tableOID int64
	err = conn.QueryRow(t.Context(), `SELECT c.oid FROM pg_catalog.pg_class c LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind IN ('r', 'v', 'm', 'f', 'p')`, "public", "ad_bids_metrics_view").Scan(&tableOID)
	require.NoError(t, err)
	rows, err := conn.Query(t.Context(), `SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod) FROM pg_catalog.pg_attribute a WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`, strconv.FormatInt(tableOID, 10))
	require.NoError(t, err)
	var columns [][2]string
	for rows.Next() {
		var name, typ string
		require.NoError(t, rows.Scan(&name, &typ))
		columns = append(columns, [2]string{name, typ})
	}
	require.NoError(t, rows.Err())
	rows.Close()
	require.Equal(t, [][2]string{
		{"timestamp", "timestamp with time zone"},
		{"publisher", "character varying"},
		{"domain", "character varying"},
		{"total_records", "double precision"},
		{"bid_price_sum", "double precision"},
	}, columns)

	// This is the time-grain query generated by Superset's chart API.
	rows, err = conn.Query(t.Context(), `SELECT DATE_TRUNC('day', timestamp) AS timestamp, total_records AS total_records FROM public.ad_bids_metrics_view GROUP BY DATE_TRUNC('day', timestamp) ORDER BY timestamp ASC LIMIT 5`)
	require.NoError(t, err)
	var timestamps []time.Time
	for rows.Next() {
		var timestamp time.Time
		var totalRecords int64
		require.NoError(t, rows.Scan(&timestamp, &totalRecords))
		timestamps = append(timestamps, timestamp)
		require.Positive(t, totalRecords)
	}
	require.NoError(t, rows.Err())
	rows.Close()
	require.Len(t, timestamps, 5)
	require.Equal(t, time.Date(2022, time.January, 1, 0, 0, 0, 0, time.UTC), timestamps[0].UTC())
}

func TestRuntimeSessionMetricsSQLAndCatalog(t *testing.T) {
	rt, instanceID := testruntime.NewInstanceForProject(t, "ad_bids")
	session, err := NewSession(rt, instanceID, &runtime.SecurityClaims{Permissions: runtime.AllPermissions, SkipChecks: true})
	require.NoError(t, err)
	defer session.Close()

	rows, err := session.Query(context.Background(), "SELECT pub, dom FROM ad_bids_metrics WHERE dom = 'msn.com' LIMIT 1", nil, nil)
	require.NoError(t, err)
	require.True(t, rows.Next())
	require.Len(t, rows.Values(), 2)
	require.NoError(t, rows.Close())

	// Representative Metabase information_schema probe.
	rows, err = session.Query(context.Background(), "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ad_bids_metrics'", nil, nil)
	require.NoError(t, err)
	require.True(t, rows.Next())
	require.Equal(t, "ad_bids_metrics", string(rows.Values()[0]))
	require.False(t, rows.Next())
	require.NoError(t, rows.Err())
	require.NoError(t, rows.Close())

	// Representative Superset/SQLAlchemy pg_catalog probes. SQLAlchemy resolves
	// a table OID first and looks up its columns in a separate query, so catalog
	// OIDs and column order must remain stable across catalog database rebuilds.
	rows, err = session.Query(context.Background(), `SELECT c.oid FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'ad_bids_metrics_view'`, nil, nil)
	require.NoError(t, err)
	require.True(t, rows.Next())
	tableOID := string(rows.Values()[0])
	require.NoError(t, rows.Close())

	rows, err = session.Query(context.Background(), `SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod) FROM pg_catalog.pg_attribute a WHERE a.attrelid = `+tableOID+` AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`, nil, nil)
	require.NoError(t, err)
	var columns [][2]string
	for rows.Next() {
		columns = append(columns, [2]string{string(rows.Values()[0]), string(rows.Values()[1])})
	}
	require.NoError(t, rows.Err())
	require.NoError(t, rows.Close())
	require.Equal(t, [][2]string{
		{"timestamp", "timestamp with time zone"},
		{"publisher", "character varying"},
		{"domain", "character varying"},
		{"total_records", "double precision"},
		{"bid_price_sum", "double precision"},
	}, columns)

	_, err = session.Query(context.Background(), "SELECT * FROM missing_metrics_view", nil, nil)
	require.Error(t, err)
}
