<script lang="ts">
  import type { EditorView } from "@codemirror/view";
  import { setLineStatuses } from "@rilldata/web-common/components/editor/line-status";
  import type { V1ParseError } from "@rilldata/web-common/runtime-client";
  import { yamlSchema } from "codemirror-json-schema/yaml";
  import { mapParseErrorsToLines } from "../../errors";
  import MetricsEditorContainer from "./MetricsEditorContainer.svelte";
  import { createPlaceholder } from "./create-placeholder";
  import metricsSchema from "./metrics-schema.json";
  import { JSONSchema7 } from "json-schema";
  import Editor from "@rilldata/web-common/features/editor/Editor.svelte";
  import { FileArtifact } from "@rilldata/web-common/features/entity-management/file-artifacts";
  import { metricsExplorerStore } from "@rilldata/web-common/features/dashboards/stores/dashboard-stores";
  import { createPersistentDashboardStore } from "@rilldata/web-common/features/dashboards/stores/persistent-dashboard-state";

  export let filePath: string;
  export let metricViewName: string;
  export let allErrors: V1ParseError[];
  export let fileArtifact: FileArtifact;

  $: ({ remoteContent } = fileArtifact);

  let editor: EditorView;
  const metricsJsonSchema = metricsSchema as JSONSchema7;

  /** create placeholder codemirror extension and set the inner svelte component
   * generated by the createPlaceholder callback.
   */
  $: placeholderElements = createPlaceholder(filePath, metricViewName);
  $: if (editor) placeholderElements.component.setEditorView(editor);

  $: lineBasedRuntimeErrors = mapParseErrorsToLines(allErrors, $remoteContent);
  /** display the main error (the first in this array) at the bottom */
  $: mainError = lineBasedRuntimeErrors?.at(0);

  /** If the errors change, run the following transaction. */
  $: if (editor) setLineStatuses(lineBasedRuntimeErrors, editor);
</script>

<MetricsEditorContainer error={$remoteContent ? mainError : undefined}>
  <Editor
    bind:editor
    onSave={(content) => {
      if (!content?.length) {
        setLineStatuses([], editor);
      }
      // Remove the explorer entity so that everything is reset to defaults next time user navigates to it
      metricsExplorerStore.remove(metricViewName);
      // Reset local persisted dashboard state for the metrics view
      createPersistentDashboardStore(metricViewName).reset();
    }}
    {fileArtifact}
    extensions={[placeholderElements.extension, yamlSchema(metricsJsonSchema)]}
  />
</MetricsEditorContainer>
