version: 2

project_name: rill

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cli/main.go
    binary: rill
    goos:
      - ${GOOS}
    goarch:
      - ${GOARCH}
    env:
      - >-
        {{- if eq .Os "darwin" }}CC=clang{{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-linux-gnu-gcc{{- end }}
          {{- if eq .Arch "arm64" }}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}
      - >-
        {{- if eq .Os "darwin" }}CXX=clang++{{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CXX=x86_64-linux-gnu-gcc{{- end }}
          {{- if eq .Arch "arm64" }}CXX=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}
    flags:
      - "-mod=readonly"
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.Commit={{ .ShortCommit }} -X main.BuildDate={{ .Date }}

blobs:
  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/v{{ .Version }}"
    extra_files:
      - glob: ./dist/**/*

  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/latest"
    extra_files:
      - glob: ./dist/**/*

{{- if and (eq .Os "linux") (eq .Arch "amd64") }}
dockers:
  - image_templates:
      - rilldata/rill:latest
      - rilldata/rill:{{ .Tag }}
{{- end }}

checksum:
  name_template: checksums_{{ .Env.BUILD }}.txt

snapshot:
  name_template: "{{ incminor .Version }}-nightly"
