version: 2

project_name: rill

release:
  prerelease: auto
  draft: false

before:
  hooks:
    - go mod tidy
    - echo {{ .Env.DOCKERHUB_PASS }} | docker login -u {{ .Env.DOCKERHUB_USER }} --password-stdin

builds:
  - id: linux
    main: ./cli/main.go
    binary: rill
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - "-mod=readonly"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.BuildDate={{.Date}}

blobs:
  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/v{{ .Version }}"
    extra_files:
      - glob: ./dist/**/*

  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/latest"
    extra_files:
      - glob: ./dist/**/*

brews:
  - homepage: https://github.com/rilldata/rill
    description: The Rill CLI
    name: rill
    license: Apache 2.0
    url_template: https://cdn.rilldata.com/rill/{{ .Tag }}/{{ .ArtifactName }}
    repository:
      owner: rilldata
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    test: |
      system "#{bin}/rill --version"
    install: |
      bin.install "rill"
    commit_author:
      name: rilldata
      email: support@rilldata.com

dockers:
  - image_templates:
      - rilldata/rill:latest
      - rilldata/rill:{{ .Tag }}
    skip_push: true

archives:
  - files:
      - README.md
      - LICENSE*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: ["zip"]

checksum:
  name_template: checksums_linux_amd64.txt

snapshot:
  version_template: "{{ incminor .Version }}-nightly"

changelog:
  sort: asc
