version: 2

project_name: rill

before:
  hooks:
    - go mod tidy

builds:
  - id: {{.Env.GOOS}}_{{.Env.GOARCH}}
    main: ./cli/main.go
    binary: rill
    goos:
      - {{.Env.GOOS}}
    goarch:
      - {{.Env.GOARCH}}
    env:
      - CC={{.Env.CC}}
      - CXX={{.Env.CXX}}
    flags:
      - "-mod=readonly"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.BuildDate={{.Date}}

blobs:
  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/v{{ .Version }}"
    extra_files:
      - glob: ./dist/**/*

  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/latest"
    extra_files:
      - glob: ./dist/**/*

dockers:
  - image_templates:
      - rilldata/rill:latest
      - rilldata/rill:{{ .Tag }}

checksum:
  name_template: checksums_{{.Env.GOOS}}_{{.Env.GOARCH}}.txt

snapshot:
  name_template: "{{ incminor .Version }}-nightly"
