version: 2

project_name: rill

release:
  prerelease: auto
  draft: false

builds:
  - builder: prebuilt
    main: ./cli/main.go
    binary: rill
    goos:
      - {{.Env.GOOS}}
    goarch:
      - {{.Env.GOARCH}}
    env:
      - CC={{.Env.CC}}
      - CXX={{.Env.CXX}}
    flags:
      - "-mod=readonly"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.BuildDate={{.Date}}

brews:
  - homepage: https://github.com/rilldata/rill
    description: The Rill CLI
    name: rill
    license: Apache 2.0
    url_template: https://cdn.rilldata.com/rill/{{ .Tag }}/{{ .ArtifactName }}
    repository:
      owner: rilldata
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    test: |
      system "#{bin}/rill --version"
    install: |
      bin.install "rill"
    commit_author:
      name: rilldata
      email: support@rilldata.com

archives:
  - files:
      - README.md
      - LICENSE*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip

checksum:
  name_template: checksums_{{.Env.GOOS}}_{{.Env.GOARCH}}.txt

snapshot:
  name_template: "{{ incminor .Version }}-nightly"

changelog:
  sort: asc
