version: 2

project_name: rill

before:
  hooks:
    - go mod tidy

builds:
  - id: linux_aarch64
    main: ./cli/main.go
    binary: rill
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "-mod=readonly"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.BuildDate={{.Date}}

blobs:
  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/v{{ .Version }}"
    extra_files:
      - glob: ./dist/**/*

  - provider: gs
    bucket: prod-cdn.rilldata.com
    directory: "rill/latest"
    extra_files:
      - glob: ./dist/**/*

archives:
  - files:
      - README.md
      - LICENSE*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip

checksum:
  name_template: checksums_linux_arm64.txt

snapshot:
  name_template: "{{ incminor .Version }}-nightly"

changelog:
  sort: asc
