SELECT 
    generate_series AS record_id,
    current_date - (random() * 180)::int AS observation_date,
    ['New York', 'London', 'Tokyo', 'Sydney', 'Mumbai'][((random() * 5)::int + 1)] AS city,
    ['Sunny', 'Cloudy', 'Rainy', 'Snowy', 'Windy'][((random() * 5)::int + 1)] AS weather_condition,
    (random() * 40 - 10)::decimal(4,2) AS temperature_celsius,
    (random() * 100)::int AS humidity_percentage,
    (random() * 100)::int AS wind_speed_kmh,
    (random() * 50)::int AS precipitation_mm,
    (random() * 1000)::decimal(10,2) AS air_pressure_hpa,
    random() < 0.1 AS storm_warning,
    random() < 0.05 AS flood_warning,
    random() < 0.03 AS heatwave_warning,
    ['Morning', 'Afternoon', 'Evening', 'Night'][((random() * 4)::int + 1)] AS time_of_day,
    (random() * 5)::int AS uv_index,
    (random() * 100)::int AS visibility_km,
    (random() * 100)::int AS cloud_coverage_percentage,
    ['North', 'South', 'East', 'West'][((random() * 4)::int + 1)] AS wind_direction,
    (random() * 500)::int AS air_quality
FROM generate_series(1, 5000)