import { describe, it, expect } from "vitest";
import { MethodKind } from "@bufbuild/protobuf";
import {
  generateServiceFile,
  generateIndex,
  extractMethods,
  type ServiceDef,
} from "./generate-query-hooks";

// --- Mock service descriptors ---

class FakeRequestWithInstanceId {
  static typeName = "rill.runtime.v1.FakeRequestWithInstanceId";
  instanceId = "";
}

class FakeRequestWithoutInstanceId {
  static typeName = "rill.runtime.v1.FakeRequestWithoutInstanceId";
}

class FakeResponse {
  static typeName = "rill.runtime.v1.FakeResponse";
}

/**
 * A minimal service with one query (with instanceId), one mutation
 * (without instanceId), and one streaming method (should be skipped).
 */
const mockService: ServiceDef = {
  typeName: "rill.runtime.v1.RuntimeService",
  methods: {
    getFoo: {
      name: "GetFoo",
      I: FakeRequestWithInstanceId,
      O: FakeResponse,
      kind: MethodKind.Unary,
    },
    putBar: {
      name: "PutBar",
      I: FakeRequestWithoutInstanceId,
      O: FakeResponse,
      kind: MethodKind.Unary,
    },
    watchBaz: {
      name: "WatchBaz",
      I: FakeRequestWithInstanceId,
      O: FakeResponse,
      kind: MethodKind.ServerStreaming,
    },
  },
};

// --- extractMethods ---

describe("extractMethods", () => {
  it("returns MethodInfo for unary methods only", () => {
    const methods = extractMethods(mockService);
    const keys = methods.map((m) => m.methodKey);
    expect(keys).toContain("getFoo");
    expect(keys).toContain("putBar");
    expect(keys).not.toContain("watchBaz");
  });

  it("classifies methods correctly", () => {
    const methods = extractMethods(mockService);
    const getFoo = methods.find((m) => m.methodKey === "getFoo");
    const putBar = methods.find((m) => m.methodKey === "putBar");
    expect(getFoo?.classification).toBe("query");
    expect(putBar?.classification).toBe("mutation");
  });

  it("detects hasInstanceId", () => {
    const methods = extractMethods(mockService);
    const getFoo = methods.find((m) => m.methodKey === "getFoo");
    const putBar = methods.find((m) => m.methodKey === "putBar");
    expect(getFoo?.hasInstanceId).toBe(true);
    expect(putBar?.hasInstanceId).toBe(false);
  });

  it("extracts short type names", () => {
    const methods = extractMethods(mockService);
    const getFoo = methods.find((m) => m.methodKey === "getFoo");
    expect(getFoo?.inputType).toBe("FakeRequestWithInstanceId");
    expect(getFoo?.outputType).toBe("FakeResponse");
    expect(getFoo?.methodName).toBe("GetFoo");
  });
});

// --- generateServiceFile ---

describe("generateServiceFile", () => {
  const output = generateServiceFile(mockService);

  it("starts with the DO NOT EDIT header", () => {
    expect(output).toMatch(/^\/\/ Generated by generate-query-hooks\.ts/);
  });

  it("imports stripUndefined", () => {
    expect(output).toContain(
      'import { stripUndefined } from "../strip-undefined"',
    );
  });

  describe("query method (getFoo)", () => {
    it("generates 4 tiers: raw function, query key, query options, hook", () => {
      expect(output).toContain("export async function runtimeServiceGetFoo(");
      expect(output).toContain(
        "export function getRuntimeServiceGetFooQueryKey(",
      );
      expect(output).toContain(
        "export function getRuntimeServiceGetFooQueryOptions<",
      );
      expect(output).toContain("export function createRuntimeServiceGetFoo<");
    });

    it("uses Omit for instanceId request type", () => {
      // The raw function signature should wrap the request type in Omit
      expect(output).toMatch(
        /runtimeServiceGetFoo\(\s*client: RuntimeClient,\s*request: Omit</,
      );
    });

    it("injects instanceId in the request spread", () => {
      expect(output).toContain("instanceId: client.instanceId, ...request");
    });
  });

  describe("mutation method (putBar)", () => {
    it("generates 3 tiers: raw function, mutation options, mutation hook", () => {
      expect(output).toContain("export async function runtimeServicePutBar(");
      expect(output).toContain(
        "export function getRuntimeServicePutBarMutationOptions(",
      );
      expect(output).toContain(
        "export function createRuntimeServicePutBarMutation(",
      );
    });

    it("does not generate query key or query options", () => {
      expect(output).not.toContain("getRuntimeServicePutBarQueryKey");
      expect(output).not.toContain("getRuntimeServicePutBarQueryOptions");
    });

    it("does not use Omit (no instanceId)", () => {
      // The putBar lines should not contain Omit
      const putBarSection = output.slice(
        output.indexOf("runtimeServicePutBar("),
        output.indexOf("getRuntimeServicePutBarMutationOptions"),
      );
      expect(putBarSection).not.toContain("Omit");
    });
  });

  describe("streaming method (watchBaz)", () => {
    it("is not present in the output", () => {
      expect(output).not.toContain("watchBaz");
      expect(output).not.toContain("WatchBaz");
    });
  });
});

// --- generateIndex ---

describe("generateIndex", () => {
  it("generates barrel exports in kebab-case", () => {
    const output = generateIndex(["QueryService", "RuntimeService"]);
    expect(output).toContain('export * from "./query-service"');
    expect(output).toContain('export * from "./runtime-service"');
  });

  it("includes the DO NOT EDIT header", () => {
    const output = generateIndex(["QueryService"]);
    expect(output).toMatch(/^\/\/ Generated by generate-query-hooks\.ts/);
  });
});
