<script lang="ts">
  import type { EditorView } from "@codemirror/view";
  import { setLineStatuses } from "@rilldata/web-common/components/editor/line-status";
  import { metricsPlusSQL } from "@rilldata/web-common/components/editor/presets/yamlWithJsonAndSql";
  import { clearExploreViewState } from "@rilldata/web-common/features/dashboards/state-managers/loaders/explore-web-view-store";
  import { clearLastVisitedState } from "@rilldata/web-common/features/dashboards/state-managers/loaders/last-visited-state";
  import { metricsExplorerStore } from "@rilldata/web-common/features/dashboards/stores/dashboard-stores";
  import Editor from "@rilldata/web-common/features/editor/Editor.svelte";
  import { FileArtifact } from "@rilldata/web-common/features/entity-management/file-artifact";
  import { fileArtifacts } from "@rilldata/web-common/features/entity-management/file-artifacts";
  import { ResourceKind } from "@rilldata/web-common/features/entity-management/resource-selectors";
  import { mapParseErrorToLine } from "@rilldata/web-common/features/metrics-views/errors";
  import WorkspaceEditorContainer from "@rilldata/web-common/layout/workspace/WorkspaceEditorContainer.svelte";
  import type { V1ParseError } from "@rilldata/web-common/runtime-client";
  import { yamlSchema } from "codemirror-json-schema/yaml";
  import type { JSONSchema7 } from "json-schema";
  import { createPlaceholder } from "./create-placeholder";
  import metricsSchema from "./metrics-schema.json";

  export let filePath: string;
  export let metricsViewName: string;
  export let parseError: V1ParseError | undefined = undefined;
  export let rootCauseReconcileError: string | undefined = undefined;
  export let fileArtifact: FileArtifact;
  export let autoSave: boolean;

  $: ({ remoteContent } = fileArtifact);

  let editor: EditorView;
  const metricsJsonSchema = metricsSchema as JSONSchema7;

  /** create placeholder codemirror extension and set the inner svelte component
   * generated by the createPlaceholder callback.
   */
  $: placeholderElements = createPlaceholder(filePath, metricsViewName);
  $: if (editor) placeholderElements.component.setEditorView(editor);

  /** If the parse error changes, update the editor gutter. */
  $: lineStatus = mapParseErrorToLine(parseError, $remoteContent ?? "");
  $: if (editor) setLineStatuses(lineStatus ? [lineStatus] : [], editor);
</script>

<WorkspaceEditorContainer
  error={parseError?.message ?? rootCauseReconcileError}
>
  <Editor
    bind:autoSave
    bind:editor
    onSave={(content) => {
      // Remove the explorer entity so that everything is reset to defaults next time user navigates to it
      metricsExplorerStore.remove(metricsViewName);
      clearExploreViewState(metricsViewName, undefined);
      clearLastVisitedState(metricsViewName);

      // Reset in-memory explore state derived from this metrics view
      fileArtifacts
        .getNamesForKind(ResourceKind.Explore)
        .forEach((resourceName) => {
          clearExploreViewState(resourceName, undefined);
          clearLastVisitedState(resourceName);
        });
      if (!content?.length) {
        setLineStatuses([], editor);
      }
    }}
    {fileArtifact}
    extensions={[
      metricsPlusSQL,
      placeholderElements.extension,
      yamlSchema(metricsJsonSchema),
    ]}
  />
</WorkspaceEditorContainer>
