import { ScrubBoxColor } from "@rilldata/web-common/features/dashboards/time-series/chart-colors";
import type { View } from "svelte-vega";
import type { SelectionParameter } from "vega-lite/types_unstable/selection.js";
import { resolveCSSVariable } from "./util";

/**
 * Creates a Vega-Lite brush parameter for interval selection on the x-axis.
 * Add this to a layer's `params` array to enable brush/scrub selection.
 */
export function createBrushParam(): SelectionParameter {
  const scrubColor = resolveCSSVariable(ScrubBoxColor);
  return {
    name: "brush",
    select: {
      type: "interval",
      zoom: false,
      encodings: ["x"],
      mark: {
        fill: scrubColor,
        fillOpacity: 0.4,
        stroke: scrubColor,
        strokeWidth: 1,
        strokeOpacity: 1,
      },
    },
  };
}

/**
 * Known non-temporal brush signals generated by Vega-Lite's interval selection.
 * The temporal signal (e.g. brush_yearmonthdatehours___time) is the one NOT in this set.
 */
const KNOWN_NON_TEMPORAL_BRUSH_SIGNALS = new Set([
  "brush",
  "brush_x",
  "brush_tuple",
  "brush_scale_trigger",
  "brush_tuple_fields",
  "brush_translate_anchor",
  "brush_translate_delta",
  "brush_zoom_anchor",
  "brush_zoom_delta",
  "brush_modify",
]);

/**
 * Discovers the temporal brush signal name from a live Vega view.
 *
 * Vega-Lite generates `brush_[timeunit_]<fieldname>` as the reactive temporal
 * interval signal. We find it by enumerating the view's signals and looking for
 * the brush_ signal that isn't one of the known structural signals.
 *
 * If `brushTemporalField` (from usermeta) is provided, we prefer the signal
 * whose name ends with that field name for a precise match.
 */
export function discoverTemporalBrushSignal(
  view: View,
  brushTemporalField?: string,
): string | undefined {
  const signalNames = Object.keys(view.getState().signals);
  const candidates = signalNames.filter(
    (name) =>
      name.startsWith("brush_") && !KNOWN_NON_TEMPORAL_BRUSH_SIGNALS.has(name),
  );

  if (brushTemporalField) {
    return candidates.find((name) => name.endsWith(brushTemporalField));
  }

  return candidates[0];
}
