<script lang="ts">
  import CaretDownIcon from "@rilldata/web-common/components/icons/CaretDownIcon.svelte";
  import { usePivotForExplore } from "@rilldata/web-common/features/dashboards/pivot/pivot-data-store";
  import { getStateManagers } from "@rilldata/web-common/features/dashboards/state-managers/state-managers";
  import { sanitiseExpression } from "@rilldata/web-common/features/dashboards/stores/filter-utils";
  import { useTimeControlStore } from "@rilldata/web-common/features/dashboards/time-controls/time-control-store";
  import Resizer from "@rilldata/web-common/layout/Resizer.svelte";
  import { formatCompactInteger } from "@rilldata/web-common/lib/formatters";
  import type { TimeRangeString } from "@rilldata/web-common/lib/time/types";
  import {
    createQueryServiceMetricsViewAggregation,
    type V1Expression,
    type V1MetricsViewAggregationResponseDataItem,
  } from "@rilldata/web-common/runtime-client";
  import { runtime } from "@rilldata/web-common/runtime-client/runtime-store";
  import { get } from "svelte/store";
  import { useExploreState } from "web-common/src/features/dashboards/stores/dashboard-stores";
  import ExportMenu from "../../exports/ExportMenu.svelte";
  import { featureFlags } from "../../feature-flags";
  import { mergeDimensionAndMeasureFilters } from "../filters/measure-filters/measure-filter-utils";
  import RowsViewer from "./RowsViewer.svelte";

  const { exports } = featureFlags;
  const timeControlsStore = useTimeControlStore(getStateManagers());

  export let metricsViewName: string;
  export let exploreName: string;

  const DEFAULT_LABEL = "Model Data";
  const INITIAL_HEIGHT_EXPANDED = 300;
  const MIN_HEIGHT_EXPANDED = 30;
  const MAX_HEIGHT_EXPANDED = 1000;
  const PIVOT_HEIGHT_EXPANDED = 200;

  let isOpen = false;
  let rowCountlabel = "";
  let label = DEFAULT_LABEL;
  let height = INITIAL_HEIGHT_EXPANDED;

  let manualClose = false;

  const stateManagers = getStateManagers();

  $: ({ instanceId } = $runtime);

  $: exploreState = useExploreState(exploreName);
  $: pivotDataStore = usePivotForExplore(stateManagers);
  $: showPivot = $exploreState.pivot.active;
  $: activeCellFilters = $pivotDataStore.activeCellFilters;
  $: hasDimensionThresholdFilters =
    $exploreState.dimensionThresholdFilters.length > 0;

  let filters: V1Expression | undefined;
  let timeRange: TimeRangeString = {
    start: $timeControlsStore.timeStart,
    end: $timeControlsStore.timeEnd,
  };
  $: if (showPivot && activeCellFilters) {
    if (!isOpen && !manualClose) {
      height = PIVOT_HEIGHT_EXPANDED;
      isOpen = true;
    }
    filters = sanitiseExpression(activeCellFilters.filters, undefined);
    timeRange = activeCellFilters.timeRange;
    label = "Model data for selected cell";
  } else {
    timeRange.start = $timeControlsStore.timeStart;
    let maybeEnd = $timeControlsStore.timeEnd;
    if (maybeEnd) {
      timeRange.end = new Date(new Date(maybeEnd).valueOf() + 1).toISOString();
    }
    filters = sanitiseExpression($exploreState.whereFilter, undefined);
    label = DEFAULT_LABEL;
  }

  $: filteredTotalsQuery = createQueryServiceMetricsViewAggregation(
    instanceId,
    metricsViewName,
    {
      measures: [{ name: "count", builtinMeasure: "BUILTIN_MEASURE_COUNT" }],
      timeStart: timeRange.start,
      timeEnd: timeRange.end,
      where: filters,
    },
    {
      query: {
        queryKey: [
          "dashboardFilteredRowsCt",
          metricsViewName,
          {
            timeStart: timeRange.start,
            timeEnd: timeRange.end,
            where: filters,
          },
        ],
        enabled:
          $timeControlsStore.ready &&
          !!$exploreState?.whereFilter &&
          !hasDimensionThresholdFilters, // Not yet supported with measure filters
      },
    },
  );

  $: totalsQuery = createQueryServiceMetricsViewAggregation(
    instanceId,
    metricsViewName,
    {
      measures: [{ name: "count", builtinMeasure: "BUILTIN_MEASURE_COUNT" }],
    },
    {
      query: {
        // This should not be needed, but we are getting occasional query failures where the query gets stuck on status: 'loading' when using the autogenerated key.
        // TODO: investigate this further
        queryKey: ["dashboardAllRowsCt", metricsViewName],
        enabled: !hasDimensionThresholdFilters, // Not yet supported with measure filters
      },
    },
  );

  $: {
    if ($filteredTotalsQuery.data && $totalsQuery.data) {
      const numerator = (
        $filteredTotalsQuery.data
          ?.data as V1MetricsViewAggregationResponseDataItem
      )[0]["count"];
      const denominator = (
        $totalsQuery.data.data as V1MetricsViewAggregationResponseDataItem
      )[0]["count"];
      rowCountlabel = `${formatCompactInteger(numerator)} of ${formatCompactInteger(denominator)} rows`;
    }
  }

  function toggle() {
    manualClose = true;
    isOpen = !isOpen;
  }

  function getExportQuery() {
    return {
      metricsViewRowsRequest: {
        instanceId: get(runtime).instanceId,
        metricsViewName,
        timeStart: timeRange.start,
        timeEnd: timeRange.end,
        where: sanitiseExpression(
          mergeDimensionAndMeasureFilters(
            $exploreState.whereFilter,
            $exploreState.dimensionThresholdFilters,
          ),
          undefined,
        ),
      },
    };
  }
</script>

<div
  class="relative w-full flex-none overflow-hidden flex flex-col bg-gray-100"
>
  {#if hasDimensionThresholdFilters}
    <div class="bar flex items-center gap-2">
      <span class="font-bold">Model Data</span>
      <span class="text-gray-500 font-medium">
        Not yet supported for measure-based dimension filters.
      </span>
    </div>
  {:else}
    <Resizer
      disabled={!isOpen}
      dimension={height}
      min={MIN_HEIGHT_EXPANDED}
      max={MAX_HEIGHT_EXPANDED}
      basis={INITIAL_HEIGHT_EXPANDED}
      onUpdate={(dimension) => (height = dimension)}
      direction="NS"
    />
    <div class="bar">
      <button
        aria-label="Toggle rows viewer"
        class="text-xs text-gray-800 rounded-sm hover:bg-gray-200 h-6 px-1.5 py-px flex items-center gap-1"
        on:click={toggle}
      >
        <span class:rotate-180={isOpen}>
          <CaretDownIcon size="14px" />
        </span>
        <span class="font-bold">{label}</span>
        {rowCountlabel}
      </button>
      {#if $exports}
        <div class="ml-auto">
          <ExportMenu label="Export model data" getQuery={getExportQuery} />
        </div>
      {/if}
    </div>

    {#if isOpen}
      <RowsViewer
        {filters}
        {timeRange}
        {metricsViewName}
        {exploreName}
        {height}
      />
    {/if}
  {/if}
</div>

<style lang="postcss">
  .bar {
    @apply flex items-center px-2 h-7 w-full bg-gray-100 border-t;
  }
</style>
