<script lang="ts">
  import CaretDownIcon from "@rilldata/web-common/components/icons/CaretDownIcon.svelte";
  import { getStateManagers } from "@rilldata/web-common/features/dashboards/state-managers/state-managers";
  import { sanitiseExpression } from "@rilldata/web-common/features/dashboards/stores/filter-utils";
  import { useTimeControlStore } from "@rilldata/web-common/features/dashboards/time-controls/time-control-store";
  import { formatCompactInteger } from "@rilldata/web-common/lib/formatters";
  import { createQueryServiceMetricsViewTotals } from "@rilldata/web-common/runtime-client";
  import { runtime } from "@rilldata/web-common/runtime-client/runtime-store";
  import { useDashboardStore } from "web-common/src/features/dashboards/stores/dashboard-stores";
  import ExportModelDataButton from "./ExportModelDataButton.svelte";
  import RowsViewer from "./RowsViewer.svelte";
  import Resizer from "@rilldata/web-common/layout/Resizer.svelte";

  export let metricViewName: string;

  const INITIAL_HEIGHT_EXPANDED = 300;
  const MIN_HEIGHT_EXPANDED = 30;
  const MAX_HEIGHT_EXPANDED = 1000;

  let isOpen = false;
  let label = "";
  let height = INITIAL_HEIGHT_EXPANDED;

  $: totalsQuery = createQueryServiceMetricsViewTotals(
    $runtime.instanceId,
    metricViewName,
    {
      measureNames: ["count"],
      inlineMeasures: [
        {
          name: "count",
          expression: "count(*)",
        },
      ],
    },
    {
      query: {
        // This should not be needed, but we are getting occasional query failures where the query gets stuck on status: 'loading' when using the autogenerated key.
        // TODO: investigate this further
        queryKey: ["dashboardAllRowsCt", metricViewName],
        enabled: true,
      },
    },
  );

  $: dashboardStore = useDashboardStore(metricViewName);
  const timeControlsStore = useTimeControlStore(getStateManagers());

  let timeEnd: string;
  $: {
    let maybeEnd = $timeControlsStore.timeEnd;
    if (maybeEnd) {
      timeEnd = new Date(new Date(maybeEnd).valueOf() + 1).toISOString();
    }
  }

  $: filteredTotalsQuery = createQueryServiceMetricsViewTotals(
    $runtime.instanceId,
    metricViewName,
    {
      measureNames: ["count"],
      inlineMeasures: [
        {
          name: "count",
          expression: "count(*)",
        },
      ],
      timeStart: $timeControlsStore.timeStart,
      timeEnd,
      where: sanitiseExpression($dashboardStore?.whereFilter, undefined),
    },
    {
      query: {
        queryKey: [
          "dashboardFilteredRowsCt",
          metricViewName,
          {
            timeStart: $timeControlsStore.timeStart,
            timeEnd,
            where: sanitiseExpression($dashboardStore?.whereFilter, undefined),
          },
        ],
        enabled: $timeControlsStore.ready && !!$dashboardStore?.whereFilter,
      },
    },
  );

  $: {
    if ($totalsQuery.data && $filteredTotalsQuery.data) {
      label = `${formatCompactInteger(
        $filteredTotalsQuery.data.data?.count,
      )} of ${formatCompactInteger($totalsQuery.data.data?.count)} rows`;
    }
  }

  function toggle() {
    isOpen = !isOpen;
  }
</script>

<div class="relative w-screen flex-none overflow-hidden flex flex-col">
  <Resizer
    disabled={!isOpen}
    dimension={height}
    min={MIN_HEIGHT_EXPANDED}
    max={MAX_HEIGHT_EXPANDED}
    basis={INITIAL_HEIGHT_EXPANDED}
    onUpdate={(dimension) => (height = dimension)}
    direction="NS"
  />
  <div class="bar">
    <button
      aria-label="Toggle rows viewer"
      class="text-xs text-gray-800 rounded-sm hover:bg-gray-200 h-6 px-1.5 py-px flex items-center gap-1"
      on:click={toggle}
    >
      <span class:rotate-180={isOpen}>
        <CaretDownIcon size="14px" />
      </span>
      <span class="font-bold">Model Data</span>
      {label}
    </button>
    <div class="ml-auto">
      <ExportModelDataButton />
    </div>
  </div>

  {#if isOpen}
    <RowsViewer {metricViewName} {height} />
  {/if}
</div>

<style lang="postcss">
  .bar {
    @apply flex items-center px-2 h-7 w-full bg-gray-100 border-t;
  }
</style>
