ALTER TABLE usergroups ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE usergroups ADD COLUMN created_on TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE usergroups ADD COLUMN updated_on TIMESTAMPTZ DEFAULT now() NOT NULL;
