ALTER TABLE orgs ADD COLUMN credit_total DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE orgs ADD COLUMN credit_used DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE orgs ADD COLUMN credit_expiry TIMESTAMPTZ;
