version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: github.com/rilldata/rill/proto/gen
plugins:
  # https://github.com/sudorandom/protoc-gen-connect-openapi/tree/main?tab=readme-ov-file#options
  - remote: buf.build/community/sudorandom-connect-openapi:v0.21.2
    out: ../docs/api
    opt:
      - format=yaml
      - path=rill/admin/v1/admin-connect.openapi.yaml
      - features=connectrpc;google.api.http;protovalidate
      - trim-unused-types
      - with-google-error-detail
      - content-types=json
      - short-service-tags # AdminService instead of rill.admin.v1.AdminService
      - services=rill.admin.v1.AdminService
