version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: github.com/rilldata/rill
plugins:
  - remote: buf.build/grpc-ecosystem/openapiv2:v2.27.3
    out: ../docs/api/admin/v1
    opt:
      - logtostderr=true
      - output_format=json
      - allow_merge=true
      - merge_file_name=public
      - include_package_in_tags=true
      - disable_service_tags=true
