<script lang="ts">
  import ChartIcon from "@rilldata/web-common/features/canvas/icons/ChartIcon.svelte";
  import type { GalleryExample } from "./example-to-component";

  export let example: GalleryExample;
  export let onSelect: (example: GalleryExample) => void;

  // Some upstream descriptions contain markdown links; show just the link text.
  $: description = example.description?.replace(/\[([^\]]+)\]\([^)]*\)/g, "$1");
</script>

<button
  class="flex flex-col text-left border rounded-md overflow-hidden hover:border-primary-400 hover:shadow-sm bg-surface-card"
  onclick={() => onSelect(example)}
  title={description ?? example.title}
>
  <!-- Static SVG thumbnail, pre-rendered at snapshot time: no chart engine runs
       at gallery time, so cards render instantly. -->
  <div class="thumbnail pointer-events-none" aria-hidden="true">
    {#if example.thumbnail}
      <!-- eslint-disable-next-line svelte/no-at-html-tags -- trusted, generated by our snapshot script -->
      {@html example.thumbnail}
    {:else}
      <span class="text-fg-secondary"><ChartIcon /></span>
    {/if}
  </div>
  <div class="px-3 py-2 border-t w-full">
    <div class="text-xs font-medium truncate">{example.title}</div>
    <div class="text-[11px] text-fg-secondary truncate">
      {example.subcategory}
    </div>
  </div>
</button>

<style lang="postcss">
  .thumbnail {
    @apply h-32 w-full p-2 overflow-hidden bg-white flex items-center justify-center;
  }
  .thumbnail :global(svg) {
    @apply max-h-full max-w-full;
  }
</style>
