import { getConversationManager } from "@rilldata/web-common/features/chat/core/conversation-manager";
import { ToolName } from "@rilldata/web-common/features/chat/core/types";
import { developerChatActions } from "@rilldata/web-common/features/chat/layouts/sidebar/sidebar-store";
import { getName } from "@rilldata/web-common/features/entity-management/name-utils";
import { ResourceKind } from "@rilldata/web-common/features/entity-management/resource-selectors";
import { navigateToFile } from "@rilldata/web-common/layout/navigation/editor-routing";
import { eventBus } from "@rilldata/web-common/lib/event-bus/event-bus";
import { asyncWaitUntil, waitUntil } from "@rilldata/web-common/lib/waitUtils";
import {
  runtimeServicePutFile,
  V1ReconcileStatus,
} from "@rilldata/web-common/runtime-client";
import { runtimeServiceGetResource } from "@rilldata/web-common/runtime-client/v2/gen/runtime-service";
import type { RuntimeClient } from "@rilldata/web-common/runtime-client/v2";
import { get, writable } from "svelte/store";
import { CUSTOM_VIZ_FOLDER } from "@rilldata/web-common/features/custom-viz/params";
import type { GalleryExample } from "./example-to-component";

/**
 * AI-first gallery import: instead of writing the example into the file and asking
 * the agent to rewrite it, the example's spec is embedded in the prompt and the
 * agent authors the component from scratch. A placeholder file exists while the
 * agent works (so it shows in the nav and workspace), and the user is navigated to
 * the component only once it is fully generated and reconciles without errors.
 */

/** File path currently being generated by an example import, or null. */
export const generatingComponentFilePath = writable<string | null>(null);

const MAX_SAMPLE_ROWS_IN_PROMPT = 3;
const RECONCILE_TIMEOUT_MS = 60_000;
// How many times the agent gets its own validation errors back to fix during the import.
const MAX_FIX_ATTEMPTS = 2;

export async function importVegaExampleWithAgent(
  client: RuntimeClient,
  example: GalleryExample,
  existingComponentNames: string[],
): Promise<void> {
  const componentName = getName(
    sanitizeComponentName(example.name),
    existingComponentNames,
  );
  const filePath = `/${CUSTOM_VIZ_FOLDER}/${componentName}.yaml`;

  // Placeholder so the file shows up in the nav and workspace while the agent works.
  generatingComponentFilePath.set(filePath);
  await runtimeServicePutFile(client, {
    path: filePath,
    blob: `# Importing example using AI...\ntype: component\ndisplay_name: "${example.title}"\n`,
    create: true,
    createOnly: true,
  });

  // Navigate right away so the user watches the import progress in the workspace.
  await navigateToFile(filePath);

  try {
    const conversationManager = getConversationManager(client, {
      conversationState: "browserStorage",
      agent: ToolName.DEVELOPER_AGENT,
      surface: "developer",
    });
    conversationManager.enterNewConversationMode();
    const conversation = get(conversationManager.getCurrentConversation());

    developerChatActions.startChat(buildImportPrompt(filePath, example));

    // Wait for the stream to start, then for the agent to finish.
    await waitUntil(() => get(conversation.isStreaming));
    await waitUntil(() => !get(conversation.isStreaming), -1);

    // Validation loop: if the generated component has a parse or reconcile error,
    // feed the error back to the same conversation so the agent fixes it, up to a
    // few attempts. The user is already on the file and sees the workspace appear
    // once it reconciles cleanly.
    for (let attempt = 0; ; attempt++) {
      const error = await waitForReconcileOutcome(client, componentName, filePath);
      if (!error) break;

      if (attempt >= MAX_FIX_ATTEMPTS) {
        eventBus.emit("notification", {
          message: `Imported ${filePath}, but it still has errors — review it in the editor`,
          detail: error,
          type: "error",
        });
        break;
      }

      developerChatActions.startChat(
        `The component at ${filePath} you just created has an error: "${error}". Fix the file so it parses and reconciles cleanly, keeping all the earlier requirements (top-level custom_chart block, trivial templated metrics_sql selecting every field param the spec references, typed role-named params, encoding types matching the param types, no dataset-reshaping Vega transforms — only row-local calculate transforms the geometry needs, no invented config properties).`,
      );
      await waitUntil(() => get(conversation.isStreaming));
      await waitUntil(() => !get(conversation.isStreaming), -1);
    }
  } finally {
    generatingComponentFilePath.set(null);
  }
}

function buildImportPrompt(filePath: string, example: GalleryExample): string {
  return [
    `Create a Rill component (custom viz) at ${filePath} based on the Vega-Lite example "${example.title}" below.`,
    example.description ? `Example description: ${example.description}` : "",
    "",
    "The file MUST follow exactly this YAML skeleton — its only top-level keys are type, display_name, params, and custom_chart. Never put metrics_sql or vega_spec at the top level, and never wrap custom_chart under a renderer: key:",
    "```yaml",
    "type: component",
    'display_name: "<chart title>"',
    "params:",
    "  - name: metrics_view",
    "    type: metrics_view",
    "    required: true",
    "  # ...one required param per encoded field (dimension/measure/time_dimension),",
    "  # then order_by (unless a time series) and limit as described below",
    "custom_chart:",
    "  metrics_sql: SELECT {{ .params.<field> }}, ... FROM {{ .params.metrics_view }} ORDER BY {{ .params.order_by }} DESC LIMIT {{ .params.limit }}",
    "  vega_spec: |",
    '    {"data": {"name": "query1"}, "mark": ..., "encoding": ...}',
    "```",
    "",
    "Requirements:",
    "- The metrics_sql MUST be a single trivial statement of the form SELECT {{ .params.<dim> }}, {{ .params.<measure> }} FROM {{ .params.metrics_view }} with an ORDER BY and LIMIT. Metrics SQL is a restricted dialect: NO CTEs, JOINs, subqueries, window functions, CASE expressions, or aggregate functions (measures are already aggregated).",
    "- Make the sort customizable: declare a required string param named order_by and write ORDER BY {{ .params.order_by }} DESC (the editor offers the bound dimensions/measures as its choices and defaults it to the measure). Time-series charts instead order by the time dimension ascending, without an order_by param.",
    "- Declare a number param named limit (not required, with a default) and end the SQL with LIMIT {{ .params.limit }} so dashboards can tune the row count. Choose the default yourself from the chart's visual density: around 10 where each row is a large mark (bars, arcs, text), up to 100 for charts that stay readable with many small marks (point/circle/square scatterplots, rect heatmaps, tick plots), and up to 2000 for time series.",
    "- Every dimension/measure/time_dimension param referenced by the vega_spec encodings or by the ORDER BY MUST also appear in the SELECT list — a field can only be used if it is selected.",
    "- Declare a required param named metrics_view of type metrics_view, and one required param per encoded field typed dimension, measure, or time_dimension (never string, and no defaults). Pick the most suitable metrics view in this project for the chart's shape.",
    "- Name params after their role in the chart (x_axis, y_axis, color, size, ...), not after the example's column names, and give each a description.",
    '- Template the query and all Vega field references with {{ .params.<name> }} and bind the data as {"name": "query1"}.',
    "- Remove Vega transforms that reshape or aggregate the dataset (filter, aggregate, joinaggregate, window, stack, fold, pivot, lookup, bin, density, regression, ...) and do not reproduce their derived values in SQL — simplify the chart to direct field encodings, dropping encodings that depend on them.",
    '- KEEP row-local calculate transforms whose derived values the chart\'s geometry needs: diverging sign flips (population pyramids, diverging stacked bars), ratios/percentages, differences, midpoints, absolute values. Rewrite their datum references against the params (e.g. datum[\'{{ .params.<measure> }}\']), keep the "as" name and the encodings that read it, and expose any literal category value the expression compares against as a required string param (e.g. negate_when for the category plotted on the negative side: {"calculate": "datum[\'{{ .params.<dim> }}\'] === negate_when ? -datum[\'{{ .params.<measure> }}\'] : datum[\'{{ .params.<measure> }}\']", "as": "signed_value"}). Scalar params are injected as native Vega-Lite params, referenceable directly in expressions. Give diverging axes a labelExpr showing absolute values.',
    "- timeUnit is an encoding property, NOT a transform — preserve it. When the example derives several channels from ONE temporal field via different timeUnits (calendar heatmaps, punch cards, day/hour grids), declare a SINGLE time_dimension param and reference it from every such channel, keeping each channel's timeUnit and type exactly as in the example; select that field once in the SQL and order by it ascending with a time-series limit (up to 2000).",
    '- Match every encoding\'s "type" to the param bound to it: dimension → "nominal"/"ordinal", time_dimension → the example\'s temporal/ordinal type with its timeUnit, measure → "quantitative". Never leave "temporal" on a plain dimension (it renders NaN axes). Remove "aggregate" from encodings (measures arrive pre-aggregated) — except where a timeUnit groups several rows into one mark; there keep the example\'s aggregate.',
    '- Never "bin" a dimension param or type it "quantitative": metrics-view dimensions are categorical strings, so binning them renders a blank chart. If the example bins raw numeric axis fields (histograms, binned scatterplots), adapt: axis channels become nominal/ordinal dimension params WITHOUT bin, and count/size channels become measure params.',
    '- Keep the visual style (mark, colors, axes, legends) as close to the example as possible, with "width": "container", "height": "container" and autosize fit. Copy the example\'s mark and config blocks verbatim; do NOT invent config or sizing properties the example does not have (invalid config renders a blank chart).',
    "",
    "The example's Vega-Lite spec (its inline sample rows are only there to convey the data's shape — do not copy them into the component):",
    "```json",
    trimmedSpecForPrompt(example.spec),
    "```",
  ]
    .filter(Boolean)
    .join("\n");
}

/** The example spec with inline sample data trimmed to a few rows, to keep the prompt small. */
function trimmedSpecForPrompt(specJSON: string): string {
  try {
    const spec = JSON.parse(specJSON);
    trimDataValues(spec);
    return JSON.stringify(spec, null, 2);
  } catch {
    return specJSON;
  }
}

function trimDataValues(node: unknown) {
  if (Array.isArray(node)) {
    for (const child of node) trimDataValues(child);
    return;
  }
  if (!node || typeof node !== "object") return;
  const obj = node as Record<string, unknown>;
  if (Array.isArray(obj.values)) {
    obj.values = obj.values.slice(0, MAX_SAMPLE_ROWS_IN_PROMPT);
  }
  for (const value of Object.values(obj)) trimDataValues(value);
}

/**
 * Polls until the generated component settles, then returns null on a clean
 * reconcile, or the parse/reconcile error message to feed back to the agent.
 */
async function waitForReconcileOutcome(
  client: RuntimeClient,
  componentName: string,
  filePath: string,
): Promise<string | null> {
  let error: string | null = null;

  const settled = await asyncWaitUntil(async () => {
    // A parse error means the resource may not even exist; check the parser first.
    const parseError = await fileParseError(client, filePath);
    if (parseError) {
      error = `parse error: ${parseError}`;
      return true;
    }

    try {
      const res = await runtimeServiceGetResource(client, {
        name: { kind: ResourceKind.Component, name: componentName },
      });
      const meta = res.resource?.meta;
      if (meta?.reconcileStatus !== V1ReconcileStatus.RECONCILE_STATUS_IDLE) {
        return false;
      }
      if (meta.reconcileError) {
        error = meta.reconcileError;
      } else if (!res.resource?.component?.state?.validSpec) {
        error = "the component has no valid spec after reconciling";
      } else {
        // Templated SQL is never executed while reconciling the component alone
        // (and structural gaps are tolerated as drafts), so run static checks
        // the reconciler can't.
        const validSpec = res.resource.component.state.validSpec;
        const props = validSpec.rendererProperties as
          | Record<string, unknown>
          | undefined;
        error =
          missingRendererError(validSpec.renderer, props) ??
          missingSelectedParamsError(validSpec.params ?? [], props) ??
          invalidDimensionEncodingError(validSpec.params ?? [], props);
      }
      return true;
    } catch {
      // Resource not (yet) created and no parse error: keep waiting.
      return false;
    }
  }, RECONCILE_TIMEOUT_MS);

  if (!settled) return "the component did not reconcile in time";
  return error;
}

/**
 * Static structure check for generated components: the renderer must be a
 * custom_chart with both metrics_sql and vega_spec. A component whose YAML
 * misplaces these (top-level metrics_sql, a renderer: wrapper, no renderer at
 * all) still reconciles as a tolerated draft, so the import loop must catch it.
 * Returns an error message to feed back to the agent, or null when valid.
 */
export function missingRendererError(
  renderer: string | undefined,
  rendererProperties: Record<string, unknown> | undefined,
): string | null {
  if (!renderer) {
    return "the component has no renderer: define a TOP-LEVEL custom_chart block (a sibling of params) containing metrics_sql and vega_spec — never put metrics_sql/vega_spec at the top level of the YAML or under a renderer: key";
  }
  if (renderer !== "custom_chart") {
    return `the component uses renderer "${renderer}" but must define a TOP-LEVEL custom_chart block containing metrics_sql and vega_spec`;
  }
  if (!rendererProperties?.metrics_sql || !rendererProperties?.vega_spec) {
    return "the custom_chart block must contain both metrics_sql and vega_spec";
  }
  return null;
}

/**
 * Static consistency check for generated components: every field-typed param
 * that the vega_spec or the ORDER BY references must also be selected in the
 * metrics_sql. Ordering by an unselected field fails at query time and encodings
 * reading unselected fields render empty — but only at render time, which the
 * component's own reconcile cannot catch, so the import loop checks it here.
 * Returns an error message to feed back to the agent, or null when consistent.
 */
export function missingSelectedParamsError(
  params: Array<{ name?: string; type?: string }>,
  rendererProperties: Record<string, unknown> | undefined,
): string | null {
  const sqlProp = rendererProperties?.metrics_sql;
  const sql = Array.isArray(sqlProp) ? sqlProp.join(" ") : sqlProp;
  if (typeof sql !== "string" || !sql) return null;
  const vegaSpec = rendererProperties?.vega_spec;

  const fieldParams = new Set(
    params
      .filter(
        (param) =>
          param.type === "dimension" ||
          param.type === "measure" ||
          param.type === "time_dimension",
      )
      .map((param) => param.name ?? ""),
  );
  if (fieldParams.size === 0) return null;

  const selectListRegex = /select\s+([\s\S]*?)\s+from\s/i;
  const selected = new Set(paramRefs(selectListRegex.exec(sql)?.[1] ?? ""));
  const referenced = [
    ...paramRefs(sql.replace(selectListRegex, " ")),
    ...paramRefs(typeof vegaSpec === "string" ? vegaSpec : ""),
  ];
  const missing = [...new Set(referenced)].filter(
    (name) => fieldParams.has(name) && !selected.has(name),
  );
  if (missing.length === 0) return null;
  return `the metrics_sql must select every field param that the vega_spec or the ORDER BY references; add ${missing
    .map((name) => `{{ .params.${name} }}`)
    .join(", ")} to the SELECT list`;
}

function paramRefs(text: string): string[] {
  return [...text.matchAll(/\{\{\s*\.(?:params|args)\.(\w+)\s*\}\}/g)].map(
    (match) => match[1],
  );
}

/**
 * Static check for dimension params encoded as numeric: metrics-view dimensions
 * are categorical strings, so an encoding that bins them or types them
 * "quantitative"/"temporal" renders a blank chart (NaN bins/axes) — but only at
 * render time, which the component's own reconcile cannot catch.
 * Returns an error message to feed back to the agent, or null when consistent.
 */
export function invalidDimensionEncodingError(
  params: Array<{ name?: string; type?: string }>,
  rendererProperties: Record<string, unknown> | undefined,
): string | null {
  const vegaSpecJSON = rendererProperties?.vega_spec;
  if (typeof vegaSpecJSON !== "string") return null;
  const dimensionParams = new Set(
    params
      .filter((param) => param.type === "dimension")
      .map((param) => param.name ?? ""),
  );
  if (dimensionParams.size === 0) return null;

  let vegaSpec: unknown;
  try {
    vegaSpec = JSON.parse(vegaSpecJSON);
  } catch {
    return null; // Malformed/templated JSON is validated elsewhere.
  }

  const issues: string[] = [];
  visitFieldDefs(vegaSpec, (def, paramName) => {
    if (!dimensionParams.has(paramName)) return;
    if (def.bin) {
      issues.push(
        `the encoding bound to dimension param "${paramName}" uses "bin"`,
      );
    } else if (def.type === "quantitative" || def.type === "temporal") {
      issues.push(
        `the encoding bound to dimension param "${paramName}" has "type": "${def.type}"`,
      );
    }
  });
  if (issues.length === 0) return null;
  return `${issues.join("; ")} — dimension params are categorical strings, so their encodings must use "type": "nominal" or "ordinal" without bin (bind a measure param instead if the channel needs numeric values)`;
}

/** Walks the spec, invoking cb for each object with a templated "field" property. */
function visitFieldDefs(
  node: unknown,
  cb: (def: Record<string, unknown>, paramName: string) => void,
): void {
  if (Array.isArray(node)) {
    for (const child of node) visitFieldDefs(child, cb);
    return;
  }
  if (!node || typeof node !== "object") return;
  const obj = node as Record<string, unknown>;
  if (typeof obj.field === "string") {
    const param = /^\{\{\s*\.(?:params|args)\.(\w+)\s*\}\}$/.exec(obj.field);
    if (param) cb(obj, param[1]);
  }
  for (const value of Object.values(obj)) visitFieldDefs(value, cb);
}

/** The current parse error for a file, if any (from the project parser resource). */
async function fileParseError(
  client: RuntimeClient,
  filePath: string,
): Promise<string | null> {
  try {
    const res = await runtimeServiceGetResource(client, {
      name: { kind: ResourceKind.ProjectParser, name: "parser" },
    });
    const parseError = res.resource?.projectParser?.state?.parseErrors?.find(
      (candidate) => candidate.filePath === filePath,
    );
    return parseError?.message ?? null;
  } catch {
    return null;
  }
}

function sanitizeComponentName(name: string): string {
  const sanitized = name
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, "_")
    .replace(/^(\d)/, "_$1");
  return sanitized || "custom_viz";
}
