import { getConversationManager } from "@rilldata/web-common/features/chat/core/conversation-manager";
import { ToolName } from "@rilldata/web-common/features/chat/core/types";
import { developerChatActions } from "@rilldata/web-common/features/chat/layouts/sidebar/sidebar-store";
import { ResourceKind } from "@rilldata/web-common/features/entity-management/resource-selectors";
import { navigateToFile } from "@rilldata/web-common/layout/navigation/editor-routing";
import { eventBus } from "@rilldata/web-common/lib/event-bus/event-bus";
import { asyncWaitUntil, waitUntil } from "@rilldata/web-common/lib/waitUtils";
import {
  runtimeServicePutFile,
  V1ReconcileStatus,
} from "@rilldata/web-common/runtime-client";
import { runtimeServiceGetResource } from "@rilldata/web-common/runtime-client/v2/gen/runtime-service";
import type { RuntimeClient } from "@rilldata/web-common/runtime-client/v2";
import { get, writable } from "svelte/store";
import { componentFilePathFor } from "./component-file";
import type { GalleryEntry } from "./example-spec";

/**
 * AI-first gallery import: the chosen chart type and its channels go into the prompt and the agent
 * authors the component against the project's own metrics views. A placeholder file exists while
 * the agent works (so it shows in the nav and workspace), and the user is navigated to the
 * component only once it is fully generated and reconciles without errors.
 *
 * The deterministic import (example-spec.ts) already produces a valid component for every catalog
 * entry; the agent path exists to pick sensible fields from the project rather than leaving every
 * param unbound.
 */

/** File path currently being generated by an example import, or null. */
export const generatingComponentFilePath = writable<string | null>(null);

const RECONCILE_TIMEOUT_MS = 60_000;
// How many times the agent gets its own validation errors back to fix during the import.
const MAX_FIX_ATTEMPTS = 2;

export async function importGalleryChartWithAgent(
  client: RuntimeClient,
  entry: GalleryEntry,
  existingComponentNames: string[],
): Promise<void> {
  const { componentName, filePath } = componentFilePathFor(
    entry.chartSlug,
    existingComponentNames,
  );

  // Placeholder so the file shows up in the nav and workspace while the agent works.
  generatingComponentFilePath.set(filePath);
  await runtimeServicePutFile(client, {
    path: filePath,
    blob: `# Importing chart using AI...\ntype: component\ndisplay_name: "${entry.chartType}"\n`,
    create: true,
    createOnly: true,
  });

  // Navigate right away so the user watches the import progress in the workspace.
  await navigateToFile(filePath);

  try {
    const conversationManager = getConversationManager(client, {
      conversationState: "browserStorage",
      agent: ToolName.DEVELOPER_AGENT,
      surface: "developer",
    });
    conversationManager.enterNewConversationMode();
    const conversation = get(conversationManager.getCurrentConversation());

    developerChatActions.startChat(buildImportPrompt(filePath, entry));

    // Wait for the stream to start, then for the agent to finish.
    await waitUntil(() => get(conversation.isStreaming));
    await waitUntil(() => !get(conversation.isStreaming), -1);

    // Validation loop: if the generated component has a parse or reconcile error,
    // feed the error back to the same conversation so the agent fixes it, up to a
    // few attempts. The user is already on the file and sees the workspace appear
    // once it reconciles cleanly.
    for (let attempt = 0; ; attempt++) {
      const error = await waitForReconcileOutcome(
        client,
        componentName,
        filePath,
      );
      if (!error) break;

      if (attempt >= MAX_FIX_ATTEMPTS) {
        eventBus.emit("notification", {
          message: `Imported ${filePath}, but it still has errors — review it in the editor`,
          detail: error,
          type: "error",
        });
        break;
      }

      developerChatActions.startChat(
        `The component at ${filePath} you just created has an error: "${error}". Fix it with develop_file (type "component") so it parses and reconciles cleanly, keeping its chart type and bound channels.`,
      );
      await waitUntil(() => get(conversation.isStreaming));
      await waitUntil(() => !get(conversation.isStreaming), -1);
    }
  } finally {
    generatingComponentFilePath.set(null);
  }
}

/**
 * Beyond the example's own spec, the prompt carries only what is specific to the chosen entry. The
 * general rules of authoring a component — the file's shape, the param types, the metrics_sql
 * dialect, the encoding vocabulary — reach the sub-agent through the component resource
 * instructions that develop_file loads for `type: component`, so restating them here would only be
 * a second copy to keep in sync.
 */
function buildImportPrompt(filePath: string, entry: GalleryEntry): string {
  return [
    `Create a Rill component (custom viz) at ${filePath}, by calling develop_file with type "component" and passing every detail below in its prompt.`,
    "",
    "Use this spec, which is the example's own, verbatim — the same chart type, the same channels and no others, and the same chart properties. Declare one param per channel, typed as annotated:",
    "```yaml",
    exampleSpecYAML(entry),
    "```",
    "",
    `- Use "${entry.chartType}" as the display_name.`,
    entry.description
      ? `- The example it is based on: ${entry.description}`
      : "",
    `- Give the limit param a default of ${entry.defaultLimit}, which suits this chart's density.`,
    "- Order a time series by the time dimension ascending; order anything else by the main measure descending, without an order_by param.",
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * The gallery entry's chart spec, written out the way the component file should carry it: each
 * channel bound to a templated param and annotated with the param type it takes, and the example's
 * chartProperties preserved (a donut without its innerRadius is a pie).
 */
function exampleSpecYAML(entry: GalleryEntry): string {
  const lines = [`chartType: ${entry.chartType}`, "encodings:"];
  for (const binding of entry.bindings) {
    lines.push(
      `  ${binding.channel}: { field: "{{ .params.${binding.param} }}" } # ${binding.role} param`,
    );
  }
  if (entry.chartProperties) {
    lines.push("chartProperties:");
    for (const [key, value] of Object.entries(entry.chartProperties)) {
      lines.push(`  ${key}: ${JSON.stringify(value)}`);
    }
  }
  return lines.join("\n");
}

/**
 * Polls until the generated component settles, then returns null on a clean
 * reconcile, or the parse/reconcile error message to feed back to the agent.
 */
async function waitForReconcileOutcome(
  client: RuntimeClient,
  componentName: string,
  filePath: string,
): Promise<string | null> {
  let error: string | null = null;

  const settled = await asyncWaitUntil(async () => {
    // A parse error means the resource may not even exist; check the parser first.
    const parseError = await fileParseError(client, filePath);
    if (parseError) {
      error = `parse error: ${parseError}`;
      return true;
    }

    try {
      const res = await runtimeServiceGetResource(client, {
        name: { kind: ResourceKind.Component, name: componentName },
      });
      const meta = res.resource?.meta;
      if (meta?.reconcileStatus !== V1ReconcileStatus.RECONCILE_STATUS_IDLE) {
        return false;
      }
      if (meta.reconcileError) {
        error = meta.reconcileError;
      } else if (!res.resource?.component?.state?.validSpec) {
        error = "the component has no valid spec after reconciling";
      } else {
        // Templated SQL is never executed while reconciling the component alone
        // (and structural gaps are tolerated as drafts), so run static checks
        // the reconciler can't.
        const validSpec = res.resource.component.state.validSpec;
        const props = validSpec.rendererProperties as
          | Record<string, unknown>
          | undefined;
        error =
          missingRendererError(validSpec.renderer, props) ??
          missingSelectedParamsError(validSpec.params ?? [], props) ??
          invalidDimensionEncodingError(validSpec.params ?? [], props);
      }
      return true;
    } catch {
      // Resource not (yet) created and no parse error: keep waiting.
      return false;
    }
  }, RECONCILE_TIMEOUT_MS);

  if (!settled) return "the component did not reconcile in time";
  return error;
}

/**
 * Static structure check for generated components: the renderer must be a
 * custom_chart with both metrics_sql and spec. A component whose YAML
 * misplaces these (top-level metrics_sql, a renderer: wrapper, no renderer at
 * all) still reconciles as a tolerated draft, so the import loop must catch it.
 * Returns an error message to feed back to the agent, or null when valid.
 */
export function missingRendererError(
  renderer: string | undefined,
  rendererProperties: Record<string, unknown> | undefined,
): string | null {
  if (!renderer) {
    return "the component has no renderer: define a TOP-LEVEL custom_chart block (a sibling of params) containing metrics_sql and spec — never put metrics_sql/spec at the top level of the YAML or under a renderer: key";
  }
  if (renderer !== "custom_chart") {
    return `the component uses renderer "${renderer}" but must define a TOP-LEVEL custom_chart block containing metrics_sql and spec`;
  }
  if (!rendererProperties?.metrics_sql || !rendererProperties?.spec) {
    return "the custom_chart block must contain both metrics_sql and spec";
  }
  const spec = rendererProperties.spec as Record<string, unknown>;
  if (!spec.chartType) {
    return "the spec must set a chartType";
  }
  if (!spec.encodings || Object.keys(spec.encodings).length === 0) {
    return "the spec must bind at least one channel under encodings";
  }
  return null;
}

/**
 * Static consistency check for generated components: every field-typed param
 * that the spec or the ORDER BY references must also be selected in the
 * metrics_sql. Ordering by an unselected field fails at query time and encodings
 * reading unselected fields render empty — but only at render time, which the
 * component's own reconcile cannot catch, so the import loop checks it here.
 * Returns an error message to feed back to the agent, or null when consistent.
 */
export function missingSelectedParamsError(
  params: Array<{ name?: string; type?: string }>,
  rendererProperties: Record<string, unknown> | undefined,
): string | null {
  const sqlProp = rendererProperties?.metrics_sql;
  const sql = Array.isArray(sqlProp) ? sqlProp.join(" ") : sqlProp;
  if (typeof sql !== "string" || !sql) return null;
  // The chart spec is a nested object; serializing it is enough to find param references.
  const spec = JSON.stringify(rendererProperties?.spec ?? "");

  const fieldParams = new Set(
    params
      .filter(
        (param) =>
          param.type === "dimension" ||
          param.type === "measure" ||
          param.type === "time_dimension",
      )
      .map((param) => param.name ?? ""),
  );
  if (fieldParams.size === 0) return null;

  const selectListRegex = /select\s+([\s\S]*?)\s+from\s/i;
  const selected = new Set(paramRefs(selectListRegex.exec(sql)?.[1] ?? ""));
  const referenced = [
    ...paramRefs(sql.replace(selectListRegex, " ")),
    ...paramRefs(spec),
  ];
  const missing = [...new Set(referenced)].filter(
    (name) => fieldParams.has(name) && !selected.has(name),
  );
  if (missing.length === 0) return null;
  return `the metrics_sql must select every field param that the spec or the ORDER BY references; add ${missing
    .map((name) => `{{ .params.${name} }}`)
    .join(", ")} to the SELECT list`;
}

function paramRefs(text: string): string[] {
  return [...text.matchAll(/\{\{\s*\.(?:params|args)\.(\w+)\s*\}\}/g)].map(
    (match) => match[1],
  );
}

/**
 * Static check for encodings that override the semantics Rill already supplies. Each field's type is
 * derived from the metrics view, so a hardcoded "type" is at best redundant and at worst wrong
 * — a dimension typed "quantitative" renders a blank chart. That only shows at render time, which
 * the component's own reconcile cannot catch.
 * Returns an error message to feed back to the agent, or null when consistent.
 */
export function invalidDimensionEncodingError(
  params: Array<{ name?: string; type?: string }>,
  rendererProperties: Record<string, unknown> | undefined,
): string | null {
  const spec = rendererProperties?.spec;
  if (!spec || typeof spec !== "object") return null;

  const dimensionParams = new Set(
    params
      .filter((param) => param.type === "dimension")
      .map((param) => param.name ?? ""),
  );
  if (dimensionParams.size === 0) return null;

  const issues: string[] = [];
  visitFieldDefs(spec, (def, paramName) => {
    if (!dimensionParams.has(paramName)) return;
    if (def.type === "quantitative" || def.type === "temporal") {
      issues.push(
        `the encoding bound to dimension param "${paramName}" has "type": "${def.type}"`,
      );
    }
  });
  if (issues.length === 0) return null;
  return `${issues.join("; ")} — dimension params are categorical, and Rill already derives each field's type from the metrics view, so remove the "type" from these encodings (bind a measure param instead if the channel needs numeric values)`;
}

/** Walks the spec, invoking cb for each object with a templated "field" property. */
function visitFieldDefs(
  node: unknown,
  cb: (def: Record<string, unknown>, paramName: string) => void,
): void {
  if (Array.isArray(node)) {
    for (const child of node) visitFieldDefs(child, cb);
    return;
  }
  if (!node || typeof node !== "object") return;
  const obj = node as Record<string, unknown>;
  if (typeof obj.field === "string") {
    const param = /^\{\{\s*\.(?:params|args)\.(\w+)\s*\}\}$/.exec(obj.field);
    if (param) cb(obj, param[1]);
  }
  for (const value of Object.values(obj)) visitFieldDefs(value, cb);
}

/** The current parse error for a file, if any (from the project parser resource). */
async function fileParseError(
  client: RuntimeClient,
  filePath: string,
): Promise<string | null> {
  try {
    const res = await runtimeServiceGetResource(client, {
      name: { kind: ResourceKind.ProjectParser, name: "parser" },
    });
    const parseError = res.resource?.projectParser?.state?.parseErrors?.find(
      (candidate) => candidate.filePath === filePath,
    );
    return parseError?.message ?? null;
  } catch {
    return null;
  }
}
