package metricsview

import (
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/pingcap/tidb/pkg/parser"
	"github.com/pingcap/tidb/pkg/parser/ast"
	"github.com/pingcap/tidb/pkg/parser/format"
	"github.com/pingcap/tidb/pkg/parser/mysql"
	"github.com/pingcap/tidb/pkg/parser/opcode"
	// The parser driver provides the ValueExpr implementation and registers itself on import.
	"github.com/pingcap/tidb/pkg/parser/test_driver"
	"github.com/rilldata/rill/runtime/drivers"
)

// Limits for measure expressions.
// They guard against abusive input since expressions may be supplied by non-admin users at query time.
// The depth limit counts AST levels, not just parentheses,
// so a left-associative chain like "a + b + c" costs one level per term.
const (
	maxMeasureExpressionLength = 1024
	maxMeasureExpressionDepth  = 32
)

// measureExpressionFuncs is the allowlist of scalar functions permitted in measure expressions, with their allowed arities.
// The names and semantics are those of DuckDB, ClickHouse, Druid, BigQuery, Databricks, Snowflake and StarRocks.
// Only add functions that are available with these semantics in every supported OLAP dialect;
// where a dialect spells a function differently, add it to measureExpressionFuncOverrides.
var measureExpressionFuncs = map[string]struct{ minArgs, maxArgs int }{
	"abs":      {1, 1},
	"round":    {1, 2},
	"floor":    {1, 1},
	"ceil":     {1, 1},
	"sqrt":     {1, 1},
	"ln":       {1, 1},
	"exp":      {1, 1},
	"power":    {2, 2},
	"coalesce": {2, -1},
	"nullif":   {2, 2},
	"greatest": {2, -1},
	"least":    {2, -1},
}

// measureExpressionFuncOverrides maps a dialect to the dialect-specific spelling of an allowlisted function.
// Only functions whose default name is absent or means something else in that dialect belong here.
var measureExpressionFuncOverrides = map[string]map[string]string{
	// Pinot's "round" is a time-bucketing function, i.e. "(timeValue / roundToNearest) * roundToNearest",
	// and has no single-argument form. Decimal rounding is "roundDecimal", which has the same one- and two-argument forms as "round".
	drivers.DialectNamePinot: {"round": "roundDecimal"},
}

// MeasureExpression is a parsed and validated arithmetic expression over measure names,
// e.g. "revenue - cost" or "round(revenue / users, 2)".
// It is the safe representation of a user-supplied "ephemeral measure" expression:
// only measure references, numeric literals, NULL, basic arithmetic operators and an allowlist of scalar functions are permitted.
// SQL is generated by re-rendering the parsed tree (never by echoing the input), which prevents SQL injection.
type MeasureExpression struct {
	root measureExprNode
	refs []string
}

// MeasureExpressionRenderOptions provides dialect-specific hooks for rendering a MeasureExpression to SQL.
type MeasureExpressionRenderOptions struct {
	// Dialect is the name of the target SQL dialect, used to resolve measureExpressionFuncOverrides.
	// Defaults to the empty string, which renders every function under its default name.
	Dialect string
	// EscapeRef escapes a referenced measure name for use as an identifier. Defaults to the identity function.
	EscapeRef func(name string) string
	// SafeDivide renders a division of the two provided SQL fragments. Defaults to "(num)/(den)".
	SafeDivide func(num, den string) string
}

// ParseMeasureExpression parses an arithmetic expression over measure names.
// It uses the same TiDB SQL parser and ANSI mode as the metrics SQL compiler (see metricssql.ParseFilter),
// wrapping the expression in a synthetic SELECT statement.
// It permits only: unqualified identifiers (measure references), numeric and NULL literals,
// unary minus, the binary operators + - * / %, parentheses, and the functions in measureExpressionFuncs.
// Anything else (columns with qualifiers, strings, aggregates, subqueries, CASE, casts, comparisons, etc.) is rejected.
func ParseMeasureExpression(expr string) (*MeasureExpression, error) {
	if strings.TrimSpace(expr) == "" {
		return nil, errors.New("expression is empty")
	}
	if len(expr) > maxMeasureExpressionLength {
		return nil, fmt.Errorf("expression exceeds the maximum length of %d characters", maxMeasureExpressionLength)
	}
	if err := checkMeasureExpressionComments(expr); err != nil {
		return nil, err
	}

	p := parser.New()
	// Match the metrics SQL compiler: ANSI mode with double quotes identifying SQL identifiers.
	p.SetSQLMode(mysql.ModeANSI | mysql.ModeANSIQuotes)

	stmts, _, err := p.ParseSQL("SELECT " + expr)
	if err != nil {
		return nil, fmt.Errorf("invalid expression: %w", err)
	}
	if len(stmts) != 1 {
		return nil, errors.New("expected a single expression")
	}

	sel, ok := stmts[0].(*ast.SelectStmt)
	if !ok {
		return nil, errors.New("expected a scalar expression")
	}
	if sel.From != nil || sel.Where != nil || sel.GroupBy != nil || sel.Having != nil ||
		sel.OrderBy != nil || sel.Limit != nil || sel.With != nil || len(sel.WindowSpecs) > 0 || sel.Distinct {
		return nil, errors.New("expected a scalar expression without SQL clauses")
	}
	if sel.Fields == nil || len(sel.Fields.Fields) != 1 {
		return nil, errors.New("expected exactly one expression")
	}

	field := sel.Fields.Fields[0]
	if field.WildCard != nil {
		return nil, errors.New("expected an expression, not a wildcard")
	}
	if field.AsName.String() != "" {
		return nil, errors.New("an alias is not allowed in the expression")
	}

	me := &MeasureExpression{}
	me.root, err = me.parseNode(field.Expr, 0)
	if err != nil {
		return nil, err
	}
	if len(me.refs) == 0 {
		return nil, errors.New("expression must reference at least one measure")
	}

	return me, nil
}

// Refs returns the measure names referenced by the expression, deduplicated in order of first appearance.
func (e *MeasureExpression) Refs() []string {
	return e.refs
}

// Render generates a SQL fragment for the expression using the provided dialect hooks.
func (e *MeasureExpression) Render(opts MeasureExpressionRenderOptions) string {
	if opts.EscapeRef == nil {
		opts.EscapeRef = func(name string) string { return name }
	}
	if opts.SafeDivide == nil {
		opts.SafeDivide = func(num, den string) string { return fmt.Sprintf("(%s)/(%s)", num, den) }
	}
	return e.root.render(opts)
}

// parseNode converts a TiDB AST expression node into a measureExprNode, rejecting anything outside the whitelist.
func (e *MeasureExpression) parseNode(in ast.ExprNode, depth int) (measureExprNode, error) {
	if depth > maxMeasureExpressionDepth {
		return nil, errors.New("expression is too deeply nested")
	}

	switch node := in.(type) {
	case *ast.ColumnNameExpr:
		if node.Name == nil {
			return nil, errors.New("invalid reference in expression")
		}
		if node.Name.Schema.String() != "" || node.Name.Table.String() != "" {
			return nil, fmt.Errorf("qualified references are not allowed (found %q); reference measures by name only", restoreMeasureExprNode(node))
		}
		name := node.Name.Name.O
		if !e.hasRef(name) {
			e.refs = append(e.refs, name)
		}
		return measureExprRef{name: name}, nil
	case ast.ValueExpr:
		return parseMeasureExprValue(node)
	case *ast.UnaryOperationExpr:
		if node.Op != opcode.Minus {
			return nil, fmt.Errorf("unsupported unary operator %q", node.Op.String())
		}
		child, err := e.parseNode(node.V, depth+1)
		if err != nil {
			return nil, err
		}
		return measureExprUnary{expr: child}, nil
	case *ast.BinaryOperationExpr:
		var op string
		switch node.Op {
		case opcode.Plus:
			op = "+"
		case opcode.Minus:
			op = "-"
		case opcode.Mul:
			op = "*"
		case opcode.Div:
			op = "/"
		case opcode.Mod:
			op = "%"
		default:
			return nil, fmt.Errorf("unsupported operator %q (only + - * / %% are allowed)", node.Op.String())
		}
		left, err := e.parseNode(node.L, depth+1)
		if err != nil {
			return nil, err
		}
		right, err := e.parseNode(node.R, depth+1)
		if err != nil {
			return nil, err
		}
		return measureExprBinary{op: op, left: left, right: right}, nil
	case *ast.ParenthesesExpr:
		// Parentheses carry no semantics of their own; rendering re-parenthesizes every compound node.
		return e.parseNode(node.Expr, depth+1)
	case *ast.FuncCallExpr:
		name := node.FnName.L
		spec, ok := measureExpressionFuncs[name]
		if !ok {
			return nil, fmt.Errorf("unsupported function %q", node.FnName.O)
		}
		if len(node.Args) < spec.minArgs || (spec.maxArgs >= 0 && len(node.Args) > spec.maxArgs) {
			return nil, fmt.Errorf("function %q does not accept %d argument(s)", node.FnName.O, len(node.Args))
		}
		args := make([]measureExprNode, len(node.Args))
		for i, arg := range node.Args {
			var err error
			args[i], err = e.parseNode(arg, depth+1)
			if err != nil {
				return nil, err
			}
		}
		return measureExprFunc{name: name, args: args}, nil
	case *ast.AggregateFuncExpr:
		return nil, fmt.Errorf("aggregate function %q is not allowed; expressions combine measures that are already aggregated", node.F)
	case *ast.SubqueryExpr:
		return nil, errors.New("subqueries are not allowed in the expression")
	case *ast.CaseExpr:
		return nil, errors.New("CASE expressions are not allowed")
	default:
		return nil, fmt.Errorf("unsupported expression %q", restoreMeasureExprNode(in))
	}
}

func (e *MeasureExpression) hasRef(name string) bool {
	for _, r := range e.refs {
		if r == name {
			return true
		}
	}
	return false
}

func parseMeasureExprValue(node ast.ValueExpr) (measureExprNode, error) {
	switch val := node.GetValue().(type) {
	case nil:
		return measureExprValue{literal: "NULL"}, nil
	case int64:
		return measureExprValue{literal: strconv.FormatInt(val, 10)}, nil
	case uint64:
		return measureExprValue{literal: strconv.FormatUint(val, 10)}, nil
	case float64:
		return measureExprValue{literal: strconv.FormatFloat(val, 'g', -1, 64)}, nil
	case *test_driver.MyDecimal:
		// Decimal literals arrive as an opaque struct; validate and keep the exact decimal text.
		if _, err := strconv.ParseFloat(val.String(), 64); err != nil {
			return nil, fmt.Errorf("invalid numeric literal %q", val.String())
		}
		return measureExprValue{literal: val.String()}, nil
	case string:
		return nil, errors.New("string literals are not allowed in the expression")
	default:
		return nil, fmt.Errorf("unsupported literal %q", restoreMeasureExprNode(node))
	}
}

// checkMeasureExpressionComments rejects SQL comments (`--`, `#` and `/* ... */`) outside quoted identifiers and string literals.
// The parser would silently strip them, changing the expression's meaning:
// e.g. a typo like "revenue -- cost" or "revenue /*- cost*/" would parse as just "revenue".
// String literals are skipped so that they are reported by parseMeasureExprValue as literals rather than as comments.
func checkMeasureExpressionComments(expr string) error {
	var quote byte // The open quote character, or 0 when outside a quoted identifier or string literal.
	for i := 0; i < len(expr); i++ {
		if quote != 0 {
			if expr[i] == quote {
				quote = 0
			}
			continue
		}
		switch {
		case expr[i] == '"' || expr[i] == '\'':
			quote = expr[i]
		case expr[i] == '#':
			return errors.New(`comments are not allowed in the expression (found "#")`)
		case expr[i] == '-' && i+1 < len(expr) && expr[i+1] == '-':
			return errors.New(`comments are not allowed in the expression (found "--"); use parentheses for double negation, e.g. "a - (-b)"`)
		case expr[i] == '/' && i+1 < len(expr) && expr[i+1] == '*':
			return errors.New(`comments are not allowed in the expression (found "/*")`)
		}
	}
	return nil
}

func restoreMeasureExprNode(node ast.Node) string {
	var sb strings.Builder
	rctx := format.NewRestoreCtx(format.RestoreStringSingleQuotes|format.RestoreKeyWordUppercase|format.RestoreNameDoubleQuotes|format.RestoreStringWithoutCharset, &sb)
	_ = node.Restore(rctx)
	return sb.String()
}

// measureExprNode is a node in the validated expression tree.
type measureExprNode interface {
	render(opts MeasureExpressionRenderOptions) string
}

type measureExprRef struct {
	name string
}

func (n measureExprRef) render(opts MeasureExpressionRenderOptions) string {
	return opts.EscapeRef(n.name)
}

type measureExprValue struct {
	literal string
}

func (n measureExprValue) render(_ MeasureExpressionRenderOptions) string {
	return n.literal
}

type measureExprUnary struct {
	expr measureExprNode
}

func (n measureExprUnary) render(opts MeasureExpressionRenderOptions) string {
	return fmt.Sprintf("(-%s)", n.expr.render(opts))
}

type measureExprBinary struct {
	op    string
	left  measureExprNode
	right measureExprNode
}

func (n measureExprBinary) render(opts MeasureExpressionRenderOptions) string {
	left := n.left.render(opts)
	right := n.right.render(opts)
	if n.op == "/" {
		return opts.SafeDivide(left, right)
	}
	return fmt.Sprintf("(%s %s %s)", left, n.op, right)
}

type measureExprFunc struct {
	name string
	args []measureExprNode
}

func (n measureExprFunc) render(opts MeasureExpressionRenderOptions) string {
	args := make([]string, len(n.args))
	for i, arg := range n.args {
		args[i] = arg.render(opts)
	}
	name := n.name
	if override, ok := measureExpressionFuncOverrides[opts.Dialect][name]; ok {
		name = override
	}
	return fmt.Sprintf("%s(%s)", name, strings.Join(args, ", "))
}
