import type { MultiStepFormSchema } from "./types";

export const athenaSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  title: "Athena",
  "x-category": "warehouse",
  properties: {
    aws_access_key_id: {
      type: "string",
      title: "AWS access key ID",
      description: "AWS access key ID used to authenticate to Athena",
      "x-placeholder": "your_access_key_id",
      "x-secret": true,
      "x-env-var-name": "AWS_ACCESS_KEY_ID",
      "x-step": "connector",
    },
    aws_secret_access_key: {
      type: "string",
      title: "AWS secret access key",
      description: "AWS secret access key paired with the access key ID",
      "x-placeholder": "your_secret_access_key",
      "x-secret": true,
      "x-env-var-name": "AWS_SECRET_ACCESS_KEY",
      "x-step": "connector",
    },
    output_location: {
      type: "string",
      title: "S3 output location",
      description:
        "S3 URI where Athena should write query results (e.g., s3://bucket/path/)",
      pattern: "^s3://.+",
      errorMessage: {
        pattern: "Must be an S3 URI (e.g., s3://bucket/path/)",
      },
      "x-placeholder": "s3://bucket-name/path/",
      "x-step": "connector",
    },
    region: {
      type: "string",
      title: "AWS Region",
      description: "AWS region for Athena queries",
      "x-placeholder": "us-east-1",
      "x-step": "connector",
    },
    workgroup: {
      type: "string",
      title: "Workgroup",
      description: "Athena workgroup name",
      "x-placeholder": "primary",
      "x-step": "connector",
    },
    role_arn: {
      type: "string",
      title: "IAM Role ARN",
      description: "IAM role ARN to assume for Athena queries",
      "x-placeholder": "arn:aws:iam::123456789012:role/MyRole",
      "x-step": "connector",
      "x-advanced": true,
    },
    role_session_name: {
      type: "string",
      title: "Role Session Name",
      description: "Session name for STS AssumeRole",
      "x-placeholder": "rill-session",
      "x-step": "connector",
      "x-advanced": true,
    },
    external_id: {
      type: "string",
      title: "External ID",
      description: "External ID for cross-account role assumption",
      "x-placeholder": "your-external-id",
      "x-step": "connector",
      "x-advanced": true,
    },
    sql: {
      type: "string",
      title: "SQL",
      description: "SQL query to run against your warehouse",
      "x-placeholder": "Input SQL",
      "x-step": "explorer",
    },
    name: {
      type: "string",
      title: "Model name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z0-9_]+$",
      "x-placeholder": "my_model",
      "x-step": "explorer",
    },
  },
  required: [
    "aws_access_key_id",
    "aws_secret_access_key",
    "output_location",
    "sql",
    "name",
  ],
};
