import type { MultiStepFormSchema } from "./types";

export const clickhouseCloudSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Connection method",
      enum: ["parameters", "connection_string"],
      default: "parameters",
      description: "Choose how to connect to ClickHouse Cloud",
      "x-display": "tabs",
      "x-enum-labels": ["Username & Password", "Connection String"],
      "x-grouped-fields": {
        parameters: ["host", "port", "database", "username", "password", "cluster", "mode"],
        connection_string: ["dsn", "mode"],
      },
      "x-step": "connector",
    },
    host: {
      type: "string",
      title: "Host",
      description: "Hostname or IP address of the ClickHouse Cloud server",
      "x-placeholder": "your-instance.clickhouse.cloud",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    port: {
      type: "string",
      title: "Port",
      description: "Port number of the ClickHouse Cloud server",
      enum: [8443, 9440],
      default: 8443,
      "x-display": "select",
      "x-enum-labels": ["8443 (HTTPS)", "9440 (Native Secure)"],
      "x-hint": "ClickHouse Cloud uses secure ports only",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    username: {
      type: "string",
      title: "Username",
      description: "Username to connect to the ClickHouse Cloud server",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Password to connect to the ClickHouse Cloud server",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    database: {
      type: "string",
      title: "Database",
      description: "Name of the ClickHouse database to connect to",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    cluster: {
      type: "string",
      title: "Cluster",
      description: "Cluster name for distributed tables",
      "x-placeholder": "Cluster name",
      "x-hint": "If set, Rill will create models as distributed tables in the cluster",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
      "x-advanced": true,
    },
    mode: {
      type: "string",
      title: "Connection Mode",
      description: "Database access mode",
      enum: ["read", "readwrite"],
      default: "read",
      "x-display": "radio",
      "x-enum-labels": ["Read-only", "Read-write"],
      "x-enum-descriptions": [
        "Only read operations are allowed (recommended for security)",
        "Enable model creation and table mutations",
      ],
      "x-step": "connector",
    },
    dsn: {
      type: "string",
      title: "Connection String",
      description: "ClickHouse connection string (DSN)",
      "x-placeholder": "https://default@your-instance.clickhouse.cloud:8443/default",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "connection_string" },
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from ClickHouse",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-step": "source",
      "x-visible-if": { mode: "readwrite" },
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
      "x-visible-if": { mode: "readwrite" },
    }
  },
  allOf: [
    {
      if: { properties: { auth_method: { const: "parameters" } } },
      then: { required: ["host", "database", "user", "password"] },
    },
    {
      if: { properties: { auth_method: { const: "connection_string" } } },
      then: { required: ["dsn"] },
    },
  ],
};