import type { MultiStepFormSchema } from "./types";

export const clickhouseSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Connection type",
      enum: ["clickhouse-cloud", "self-managed", "rill-managed"],
      default: "self-managed",
      description: "Choose how to connect to ClickHouse",
      "x-display": "radio",
      "x-enum-labels": ["ClickHouse Cloud", "Self-managed", "Rill-managed"],
      "x-enum-descriptions": [
        "Connect to ClickHouse Cloud (SSL required, uses secure ports).",
        "Connect to your own self-hosted ClickHouse server.",
        "Use a managed ClickHouse instance (starts embedded ClickHouse in development).",
      ],
      "x-grouped-fields": {
        "clickhouse-cloud": ["host", "port", "username", "password", "database", "cluster", "mode"],
        "self-managed": ["host", "port_self_managed", "username", "password", "database", "ssl", "cluster", "mode"],
        "rill-managed": ["mode"],
      },
      "x-step": "connector",
    },
    host: {
      type: "string",
      title: "Host",
      description: "Hostname or IP address of the ClickHouse server",
      "x-placeholder": "your-instance.clickhouse.cloud",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["clickhouse-cloud", "self-managed"] },
    },
    port: {
      type: "number",
      title: "Port",
      description: "Port number of the ClickHouse server",
      enum: [8443, 9440],
      default: 8443,
      "x-display": "select",
      "x-enum-labels": ["8443 (HTTPS)", "9440 (Native Secure)"],
      "x-hint": "ClickHouse Cloud uses secure ports only",
      "x-step": "connector",
      "x-visible-if": { auth_method: "clickhouse-cloud" },
    },
    port_self_managed: {
      type: "number",
      title: "Port",
      description: "Port number of the ClickHouse server",
      default: 9000,
      "x-placeholder": "9000",
      "x-hint": "Default: 9000 (native TCP), 8123 (HTTP). Secure: 9440 (TCP+TLS), 8443 (HTTPS)",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed" },
    },
    username: {
      type: "string",
      title: "Username",
      description: "Username to connect to the ClickHouse server",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["clickhouse-cloud", "self-managed"] },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Password to connect to the ClickHouse server",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: ["clickhouse-cloud", "self-managed"] },
    },
    database: {
      type: "string",
      title: "Database",
      description: "Name of the ClickHouse database to connect to",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["clickhouse-cloud", "self-managed"] },
    },
    ssl: {
      type: "boolean",
      title: "SSL",
      description: "Use SSL to connect to the ClickHouse server",
      default: true,
      "x-hint": "Enable SSL for secure connections",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed" },
    },
    cluster: {
      type: "string",
      title: "Cluster",
      description: "Cluster name for distributed tables",
      "x-placeholder": "Cluster name",
      "x-hint": "If set, Rill will create models as distributed tables in the cluster",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["clickhouse-cloud", "self-managed"] },
      "x-advanced": true,
    },
    mode: {
      type: "string",
      title: "Mode",
      description: "Connection mode for the ClickHouse database",
      enum: ["read", "readwrite"],
      default: "read",
      "x-display": "select",
      "x-hint": "Set to 'readwrite' to enable model creation and table mutations",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["clickhouse-cloud", "self-managed", "rill-managed"] },
      "x-advanced": true,
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from ClickHouse",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-display": "textarea",
      "x-step": "source",
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
    },
  },
  allOf: [
    {
      if: { properties: { auth_method: { const: "clickhouse-cloud" } } },
      then: { required: ["host", "port", "username", "password", "database"] },
    },
    {
      if: { properties: { auth_method: { const: "self-managed" } } },
      then: { required: ["host", "username"] },
    },
  ],
};
