import type { MultiStepFormSchema } from "./types";

export const clickhouseCloudSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    host: {
      type: "string",
      title: "Host",
      description: "Hostname or IP address of the ClickHouse Cloud server",
      "x-placeholder": "your-instance.clickhouse.cloud",
      "x-step": "connector",
    },
    port: {
      type: "number",
      title: "Port",
      description: "Port number of the ClickHouse Cloud server",
      enum: [8443, 9440],
      default: 8443,
      "x-display": "select",
      "x-enum-labels": ["8443 (HTTPS)", "9440 (Native Secure)"],
      "x-hint": "ClickHouse Cloud uses secure ports only",
      "x-step": "connector",
    },
    username: {
      type: "string",
      title: "Username",
      description: "Username to connect to the ClickHouse Cloud server",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
    },
    password: {
      type: "string",
      title: "Password",
      description: "Password to connect to the ClickHouse Cloud server",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
    },
    database: {
      type: "string",
      title: "Database",
      description: "Name of the ClickHouse database to connect to",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
    },
    cluster: {
      type: "string",
      title: "Cluster",
      description: "Cluster name for distributed tables",
      "x-placeholder": "Cluster name",
      "x-hint": "If set, Rill will create models as distributed tables in the cluster",
      "x-step": "connector",
      "x-advanced": true,
    },
    mode: {
      type: "string",
      title: "Connection Mode",
      description: "Database access mode",
      enum: ["read", "readwrite"],
      default: "read",
      "x-display": "radio",
      "x-enum-labels": ["Read-only", "Read-write"],
      "x-enum-descriptions": [
        "Only read operations are allowed (recommended for security)",
        "Enable model creation and table mutations",
      ],
      "x-step": "connector",
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from ClickHouse",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-display": "textarea",
      "x-step": "source",
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
    },
  },
  required: ["host", "port", "username", "password", "database"],
};
