import type { MultiStepFormSchema } from "./types";

export const clickhouseSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Connection type",
      enum: ["self-managed", "rill-managed"],
      default: "self-managed",
      description: "Choose how to connect to ClickHouse",
      "x-display": "radio",
      "x-enum-labels": ["Self-managed", "Rill-managed"],
      "x-enum-descriptions": [
        "Connect to your own self-hosted ClickHouse server.",
        "Use a managed ClickHouse instance (starts embedded ClickHouse in development).",
      ],
      "x-grouped-fields": {
        "self-managed": ["connection_method"],
        "rill-managed": [],
      },
      "x-step": "connector",
    },
    connection_method: {
      type: "string",
      title: "Connection method",
      enum: ["parameters", "connection_string"],
      default: "parameters",
      description: "Choose how to provide connection details",
      "x-display": "tabs",
      "x-enum-labels": ["Enter parameters", "Enter connection string"],
      "x-grouped-fields": {
        parameters: ["host", "port", "username", "password", "database", "ssl", "cluster", "mode"],
        connection_string: ["dsn", "mode"],
      },
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed" },
    },
    host: {
      type: "string",
      title: "Host",
      description: "Hostname or IP address of the ClickHouse server",
      "x-placeholder": "your-server.clickhouse.com",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "parameters" },
    },
    port: {
      type: "number",
      title: "Port",
      description: "Port number of the ClickHouse server",
      default: 9000,
      "x-placeholder": "9000",
      "x-hint": "Default: 9000 (native TCP), 8123 (HTTP). Secure: 9440 (TCP+TLS), 8443 (HTTPS)",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "parameters" },
    },
    username: {
      type: "string",
      title: "Username",
      description: "Username to connect to the ClickHouse server",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "parameters" },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Password to connect to the ClickHouse server",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "parameters" },
    },
    database: {
      type: "string",
      title: "Database",
      description: "Name of the ClickHouse database to connect to",
      default: "default",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "parameters" },
    },
    ssl: {
      type: "boolean",
      title: "SSL",
      description: "Use SSL to connect to the ClickHouse server",
      default: true,
      "x-hint": "Enable SSL for secure connections",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "parameters" },
    },
    cluster: {
      type: "string",
      title: "Cluster",
      description: "Cluster name for distributed tables",
      "x-placeholder": "Cluster name",
      "x-hint": "If set, Rill will create models as distributed tables in the cluster",
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "parameters" },
      "x-advanced": true,
    },
    dsn: {
      type: "string",
      title: "Connection String",
      description: "ClickHouse connection string (DSN)",
      "x-placeholder": "clickhouse://username:password@host:port/database",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed", connection_method: "connection_string" },
    },
    mode: {
      type: "string",
      title: "Connection Mode",
      description: "Database access mode",
      enum: ["read", "readwrite"],
      default: "read",
      "x-display": "radio",
      "x-enum-labels": ["Read-only", "Read-write"],
      "x-enum-descriptions": [
        "Only read operations are allowed (recommended for security)",
        "Enable model creation and table mutations",
      ],
      "x-step": "connector",
      "x-visible-if": { auth_method: "self-managed" },
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from ClickHouse",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-step": "source",
      "x-visible-if": { mode: "readwrite" },
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
      "x-visible-if": { mode: "readwrite" },
    },
  },
  allOf: [
    {
      if: {
        properties: {
          auth_method: { const: "self-managed" },
          connection_method: { const: "parameters" },
        },
      },
      then: { required: ["host", "username"] },
    },
    {
      if: {
        properties: {
          auth_method: { const: "self-managed" },
          connection_method: { const: "connection_string" },
        },
      },
      then: { required: ["dsn"] },
    },
  ],
};
