import type { MultiStepFormSchema } from "./types";

export const druidSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Connection method",
      enum: ["parameters", "connection_string"],
      default: "parameters",
      description: "Choose how to connect to Druid",
      "x-display": "radio",
      "x-enum-labels": ["Connection Parameters", "Connection String"],
      "x-enum-descriptions": [
        "Provide individual connection parameters (host, port, etc.)",
        "Provide a complete Druid connection string (DSN)",
      ],
      "x-grouped-fields": {
        parameters: ["host", "port", "username", "password", "ssl"],
        connection_string: ["dsn"],
      },
      "x-step": "connector",
    },
    host: {
      type: "string",
      title: "Host",
      description: "Hostname or IP address of the Druid server",
      "x-placeholder": "localhost",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    port: {
      type: "number",
      title: "Port",
      description: "Port number of the Druid server",
      "x-placeholder": "8888",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    username: {
      type: "string",
      title: "Username",
      description: "Username to connect to the Druid server (optional)",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Password to connect to the Druid server (optional)",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    ssl: {
      type: "boolean",
      title: "Use SSL",
      description: "Use SSL to connect to the Druid server",
      default: true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    dsn: {
      type: "string",
      title: "Connection String",
      description: "Druid connection string (DSN)",
      "x-placeholder": "https://example.com/druid/v2/sql/avatica-protobuf?authentication=BASIC&avaticaUser=username&avaticaPassword=password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "connection_string" },
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from Druid",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-display": "textarea",
      "x-step": "source",
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
    },
  },
  allOf: [
    {
      if: { properties: { auth_method: { const: "parameters" } } },
      then: { required: ["host", "ssl", "sql", "name"] },
    },
    {
      if: { properties: { auth_method: { const: "connection_string" } } },
      then: { required: ["dsn", "sql", "name"] },
    },
  ],
};
