import type { MultiStepFormSchema } from "./types";

export const icebergSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  title: "Apache Iceberg",
  "x-category": "fileStore",
  "x-form-height": "tall",
  properties: {
    connection_mode: {
      type: "string",
      title: "Connection method",
      enum: ["catalog", "direct"],
      default: "catalog",
      "x-display": "tabs",
      "x-enum-labels": ["Managed Table (Catalog)", "Direct Table Path"],
      "x-ui-only": true,
      "x-tab-group": {
        catalog: [
          "catalog_type",
          "postgres_info",
          "postgres_table",
          "mysql_info",
          "mysql_table",
          "rest_info",
          "rest_uri",
          "storage_type",
          "gcs_info",
          "gcs_path",
          "s3_info",
          "s3_path",
          "azure_path",
          "azure_info",
          "local_path",
          "name",
        ],
        direct: [
          "storage_type",
          "gcs_info",
          "gcs_path",
          "s3_info",
          "s3_path",
          "azure_path",
          "azure_info",
          "local_path",
          "name",
        ],
      },
    },
    catalog_type: {
      type: "string",
      title: "Catalog Location",
      enum: ["postgres", "mysql", "rest"],
      default: "postgres",
      "x-display": "select",
      "x-select-style": "rich",
      "x-enum-labels": ["PostgreSQL", "MySQL", "Rest API"],
      "x-enum-descriptions": [
        "Read Iceberg catalog from Postgres",
        "Read Iceberg catalog from mysql",
        "Read Iceberg catalog from Rest",
      ],
      "x-ui-only": true,
      "x-grouped-fields": {
        postgres: ["postgres_info", "postgres_table"],
        mysql: ["mysql_info", "mysql_table"],
        rest: ["rest_info", "rest_uri"],
      },
      "x-step": "source",
    },
    postgres_info: {
      type: "boolean",
      title: "PostGreSQL Connector Required",
      default: true,
      "x-informational": true,
      "x-ui-only": true,
      "x-step": "source",
    },
    postgres_table: {
      type: "string",
      title: "Iceberg catalog table",
      description: "Postgres table to the Iceberg catalog",
      pattern: "",
      errorMessage: {
        pattern: "Must be a valid table",
      },
      "x-placeholder": "db.table",
      "x-step": "source",
    },
    mysql_info: {
      type: "boolean",
      title: "MySQL Connector Required",
      default: true,
      "x-informational": true,
      "x-ui-only": true,
      "x-step": "source",
    },
    mysql_table: {
      type: "string",
      title: "Iceberg catalog table",
      description: "MySQL table to the Iceberg catalog",
      pattern: "",
      errorMessage: {
        pattern: "Must be a valid table",
      },
      "x-placeholder": "db.table",
      "x-step": "source",
    },
    rest_info: {
      type: "boolean",
      title: "HTTPS Connector Required",
      default: true,
      "x-informational": true,
      "x-ui-only": true,
      "x-step": "source",
    },
    rest_uri: {
      type: "string",
      title: "Iceberg catalog table",
      description: "REST URi to the Iceberg catalog",
      pattern: "",
      errorMessage: {
        pattern: "Must be a valid URI",
      },
      "x-placeholder": "https://endpoint.com/api",
      "x-step": "source",
    },
    storage_type: {
      type: "string",
      title: "Storage backend",
      enum: ["local", "gcs", "s3", "azure"],
      default: "local",
      "x-display": "select",
      "x-select-style": "rich",
      "x-enum-labels": [
        "Local",
        "Google Cloud Storage",
        "Amazon S3",
        "Azure Blob Storage",
      ],
      "x-enum-descriptions": [
        "Read Iceberg tables from a local directory",
        "Read Iceberg tables from a GCS bucket",
        "Read Iceberg tables from an S3 bucket",
        "Read Iceberg tables from Azure Blob Storage",
      ],
      "x-ui-only": true,
      "x-grouped-fields": {
        gcs: ["gcs_info", "gcs_path"],
        s3: ["s3_info", "s3_path"],
        azure: ["azure_info", "azure_path"],
        local: ["local_path"],
      },
      "x-step": "source",
    },
    gcs_info: {
      type: "boolean",
      title: "GCS Connector Required",
      default: true,
      "x-informational": true,
      "x-ui-only": true,
      "x-step": "source",
    },
    gcs_path: {
      type: "string",
      title: "Iceberg table URI",
      description: "GCS path to the Iceberg table directory",
      pattern: "^gs://[^/]+(/.*)?$",
      errorMessage: {
        pattern: "Must be a GCS URI (e.g. gs://bucket/path/to/iceberg_table)",
      },
      "x-placeholder": "gs://bucket/path/to/iceberg_table",
      "x-step": "source",
    },
    s3_info: {
      type: "boolean",
      title: "S3 Connector Required",
      default: true,
      "x-informational": true,
      "x-ui-only": true,
      "x-step": "source",
    },
    s3_path: {
      type: "string",
      title: "Iceberg table URI",
      description: "S3 path to the Iceberg table directory",
      pattern: "^s3://[^/]+(/.*)?$",
      errorMessage: {
        pattern: "Must be an S3 URI (e.g. s3://bucket/path/to/iceberg_table)",
      },
      "x-placeholder": "s3://bucket/path/to/iceberg_table",
      "x-step": "source",
    },
    azure_info: {
      type: "boolean",
      title: "Azure Connector Required",
      default: true,
      "x-informational": true,
      "x-ui-only": true,
      "x-step": "source",
    },
    azure_path: {
      type: "string",
      title: "Iceberg table URI",
      description: "Azure path to the Iceberg table directory",
      pattern: "^azure://.+",
      errorMessage: {
        pattern:
          "Must be an Azure URI (e.g. azure://container/path/to/iceberg_table)",
      },
      "x-placeholder": "azure://container/path/to/iceberg_table",
      "x-step": "source",
    },
    local_path: {
      type: "string",
      title: "Iceberg table path",
      description: "Local filesystem path to the Iceberg table directory",
      "x-placeholder": "/path/to/iceberg_table",
      "x-step": "source",
    },
    name: {
      type: "string",
      title: "Model name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z0-9_]+$",
      "x-placeholder": "my_iceberg_model",
      "x-step": "source",
    },
  },
  required: ["name"],
  oneOf: [
    {
      title: "Managed Table (Catalog)",
      required: ["catalog"],
      not: {},
    },
    {
      title: "Direct Table Access",
      required: ["direct"],
      not: {},
    },
  ],
  allOf: [
    {
      if: { properties: { catalog_type: { const: "postgres" } } },
      then: { required: ["postgres_table"] },
    },
    {
      if: { properties: { catalog_type: { const: "mysql" } } },
      then: { required: ["mysql_table"] },
    },
    {
      if: { properties: { catalog_type: { const: "rest" } } },
      then: { required: ["rest_uri"] },
    },
    {
      if: { properties: { storage_type: { const: "gcs" } } },
      then: { required: ["gcs_path"] },
    },
    {
      if: { properties: { storage_type: { const: "s3" } } },
      then: { required: ["s3_path"] },
    },
    {
      if: { properties: { storage_type: { const: "azure" } } },
      then: { required: ["azure_path"] },
    },
    {
      if: { properties: { storage_type: { const: "local" } } },
      then: { required: ["local_path"] },
    },
  ],
};
