import type { MultiStepFormSchema } from "./types";

export const mysqlSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Authentication method",
      enum: ["parameters", "connection_string"],
      default: "parameters",
      description: "Choose how to connect to MySQL",
      "x-display": "radio",
      "x-enum-labels": ["Username & Password", "Connection String"],
      "x-enum-descriptions": [
        "Provide individual connection parameters (host, port, database, username, password).",
        "Provide a complete MySQL connection string (DSN).",
      ],
      "x-grouped-fields": {
        parameters: ["host", "port", "database", "user", "password", "sslmode"],
        connection_string: ["dsn"],
      },
      "x-step": "connector",
    },
    host: {
      type: "string",
      title: "Host",
      description: "Database server hostname or IP address",
      "x-placeholder": "localhost",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    port: {
      type: "number",
      title: "Port",
      description: "Database server port",
      default: 3306,
      "x-placeholder": "3306",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    database: {
      type: "string",
      title: "Database",
      description: "Database name",
      "x-placeholder": "my_database",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    user: {
      type: "string",
      title: "Username",
      description: "Database user",
      "x-placeholder": "root",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Database password",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    sslmode: {
      type: "string",
      title: "SSL Mode",
      description: "SSL connection mode",
      enum: ["disabled", "preferred", "required"],
      default: "preferred",
      "x-display": "select",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    dsn: {
      type: "string",
      title: "Connection String",
      description: "MySQL connection string (DSN)",
      "x-placeholder": "user:password@tcp(host:3306)/dbname?tls=preferred",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "connection_string" },
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from MySQL",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-step": "source",
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
    },
  },
  allOf: [
    {
      if: { properties: { auth_method: { const: "parameters" } } },
      then: { required: ["host", "database", "user", "password"] },
    },
    {
      if: { properties: { auth_method: { const: "connection_string" } } },
      then: { required: ["dsn"] },
    },
  ],
};
