import type { MultiStepFormSchema } from "./types";

export const pinotSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Connection method",
      enum: ["parameters", "connection_string"],
      default: "parameters",
      description: "Choose how to connect to Pinot",
      "x-display": "tabs",
      "x-enum-labels": ["Enter parameters", "Enter connection string"],
      "x-grouped-fields": {
        parameters: ["broker_host", "broker_port", "controller_host", "controller_port", "username", "password", "ssl"],
        connection_string: ["dsn"],
      },
      "x-step": "connector",
    },
    broker_host: {
      type: "string",
      title: "Broker Host",
      description: "Hostname or IP address of the Pinot broker server",
      "x-placeholder": "localhost",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    broker_port: {
      type: "number",
      title: "Broker Port",
      description: "Port number of the Pinot broker server",
      "x-placeholder": "8000",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    controller_host: {
      type: "string",
      title: "Controller Host",
      description: "Hostname or IP address of the Pinot controller server",
      "x-placeholder": "localhost",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
      "x-advanced": true,
    },
    controller_port: {
      type: "number",
      title: "Controller Port",
      description: "Port number of the Pinot controller server",
      "x-placeholder": "9000",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
      "x-advanced": true,
    },
    username: {
      type: "string",
      title: "Username",
      description: "Username to connect to the Pinot server (optional)",
      "x-placeholder": "default",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Password to connect to the Pinot server (optional)",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    ssl: {
      type: "boolean",
      title: "Use SSL",
      description: "Use SSL to connect to the Pinot server",
      default: true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    dsn: {
      type: "string",
      title: "Connection String",
      description: "Pinot connection string (DSN)",
      "x-placeholder": "http(s)://username:password@localhost:8000?controller=localhost:9000",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "connection_string" },
    },
  },
  allOf: [
    {
      if: { properties: { auth_method: { const: "parameters" } } },
      then: { required: ["broker_host", "controller_host", "ssl"] },
    },
    {
      if: { properties: { auth_method: { const: "connection_string" } } },
      then: { required: ["dsn"] },
    },
  ],
};
