import type { MultiStepFormSchema } from "./types";

export const postgresSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Connection method",
      enum: ["parameters", "connection_string"],
      default: "parameters",
      description: "Choose how to connect to PostgreSQL",
      "x-display": "tabs",
      "x-enum-labels": ["Enter parameters", "Enter connection string"],
      "x-grouped-fields": {
        parameters: ["host", "port", "dbname", "user", "password", "sslmode", "log_queries"],
        connection_string: ["dsn", "log_queries"],
      },
      "x-step": "connector",
    },
    host: {
      type: "string",
      title: "Host",
      description: "Database server hostname or IP address",
      "x-placeholder": "localhost",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    port: {
      type: "number",
      title: "Port",
      description: "Database server port",
      default: 5432,
      "x-placeholder": "5432",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    dbname: {
      type: "string",
      title: "Database",
      description: "Database name",
      "x-placeholder": "my_database",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    user: {
      type: "string",
      title: "Username",
      description: "Database user",
      "x-placeholder": "postgres",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Database password",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
    },
    sslmode: {
      type: "string",
      title: "SSL Mode",
      description: "SSL connection mode",
      enum: ["", "disable", "allow", "prefer", "require"],
      default: "",
      "x-display": "select",
      "x-step": "connector",
      "x-visible-if": { auth_method: "parameters" },
      "x-advanced": true,
    },
    dsn: {
      type: "string",
      title: "Connection String",
      description: "PostgreSQL connection string (DSN)",
      "x-placeholder": "postgres://user:password@host:5432/dbname?sslmode=require",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "connection_string" },
    },
    log_queries: {
      type: "boolean",
      title: "Log Queries",
      description: "Enable logging of all SQL queries (useful for debugging)",
      default: false,
      "x-step": "connector",
      "x-advanced": true,
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from PostgreSQL",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-step": "source",
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
    },
  },
  required: ["sql", "name"],
  allOf: [
    {
      if: { properties: { auth_method: { const: "parameters" } } },
      then: { required: ["host", "dbname", "user", "password", "sql", "name"] },
    },
    {
      if: { properties: { auth_method: { const: "connection_string" } } },
      then: { required: ["dsn", "sql", "name"] },
    },
  ],
};
