import type { MultiStepFormSchema } from "./types";

export const snowflakeSchema: MultiStepFormSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    auth_method: {
      type: "string",
      title: "Authentication method",
      enum: ["password", "keypair", "connection_string"],
      default: "password",
      description: "Choose how to authenticate to Snowflake",
      "x-display": "radio",
      "x-enum-labels": ["Username & Password", "Key Pair", "Connection String"],
      "x-enum-descriptions": [
        "Authenticate with username and password.",
        "Authenticate with RSA key pair (more secure).",
        "Provide a complete Snowflake connection string (DSN).",
      ],
      "x-grouped-fields": {
        password: ["account", "user", "password", "warehouse", "database", "schema", "role", "log_queries", "parallel_fetch_limit"],
        keypair: ["account", "user", "private_key", "private_key_passphrase", "warehouse", "database", "schema", "role", "log_queries", "parallel_fetch_limit"],
        connection_string: ["dsn", "log_queries", "parallel_fetch_limit"],
      },
      "x-step": "connector",
    },
    account: {
      type: "string",
      title: "Account",
      description: "Snowflake account identifier (e.g., abc12345.us-east-1)",
      "x-placeholder": "abc12345.us-east-1",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["password", "keypair"] },
    },
    user: {
      type: "string",
      title: "Username",
      description: "Snowflake username",
      "x-placeholder": "Enter username",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["password", "keypair"] },
    },
    password: {
      type: "string",
      title: "Password",
      description: "Snowflake password",
      "x-placeholder": "Enter password",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "password" },
    },
    private_key: {
      type: "string",
      title: "Private Key",
      description: "RSA private key in PEM format",
      "x-placeholder": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----",
      "x-display": "textarea",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "keypair" },
    },
    private_key_passphrase: {
      type: "string",
      title: "Private Key Passphrase",
      description: "Optional passphrase for encrypted private key",
      "x-placeholder": "Enter passphrase if key is encrypted",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "keypair" },
    },
    warehouse: {
      type: "string",
      title: "Warehouse",
      description: "Snowflake warehouse name",
      "x-placeholder": "COMPUTE_WH",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["password", "keypair"] },
    },
    database: {
      type: "string",
      title: "Database",
      description: "Snowflake database name",
      "x-placeholder": "MY_DATABASE",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["password", "keypair"] },
    },
    schema: {
      type: "string",
      title: "Schema",
      description: "Snowflake schema name",
      "x-placeholder": "PUBLIC",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["password", "keypair"] },
    },
    role: {
      type: "string",
      title: "Role",
      description: "Optional Snowflake role to assume",
      "x-placeholder": "ANALYST",
      "x-step": "connector",
      "x-visible-if": { auth_method: ["password", "keypair"] },
    },
    dsn: {
      type: "string",
      title: "Connection String",
      description: "Snowflake connection string (DSN)",
      "x-placeholder": "user:password@account/database/schema?warehouse=wh",
      "x-secret": true,
      "x-step": "connector",
      "x-visible-if": { auth_method: "connection_string" },
    },
    log_queries: {
      type: "boolean",
      title: "Log Queries",
      description: "Enable logging of all SQL queries (useful for debugging)",
      default: false,
      "x-step": "connector",
      "x-advanced": true,
    },
    parallel_fetch_limit: {
      type: "number",
      title: "Parallel Fetch Limit",
      description: "Maximum number of parallel fetches for query results",
      "x-placeholder": "10",
      "x-step": "connector",
      "x-advanced": true,
    },
    sql: {
      type: "string",
      title: "SQL Query",
      description: "SQL query to extract data from Snowflake",
      "x-placeholder": "SELECT * FROM my_table;",
      "x-display": "textarea",
      "x-step": "source",
    },
    name: {
      type: "string",
      title: "Model Name",
      description: "Name for the source model",
      pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "x-placeholder": "my_model",
      "x-step": "source",
    },
  },
  allOf: [
    {
      if: { properties: { auth_method: { const: "password" } } },
      then: { required: ["account", "user", "password"] },
    },
    {
      if: { properties: { auth_method: { const: "keypair" } } },
      then: { required: ["account", "user", "private_key"] },
    },
    {
      if: { properties: { auth_method: { const: "connection_string" } } },
      then: { required: ["dsn"] },
    },
  ],
};
