swagger: "2.0"
info:
  title: Rill API
  description: It is used to manage organizations, projects, deployments, users, and roles.
  version: v1
  contact:
    name: Rill Data
    url: https://rilldata.com
  license:
    name: Apache 2.0
    url: https://github.com/rilldata/rill/blob/main/LICENSE.md
tags:
  - name: AdminService
  - name: AIService
  - name: TelemetryService
host: api.rilldata.com
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
externalDocs:
  description: Rill API Reference
  url: https://docs.rilldata.com/api/admin
