// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Organization defines model for Organization.
type Organization struct {
	CreatedOn   openapi_types.Date `json:"created_on"`
	Description *string            `json:"description,omitempty"`
	Id          string             `json:"id"`
	Name        string             `json:"name"`
	UpdatedOn   openapi_types.Date `json:"updated_on"`
}

// Project defines model for Project.
type Project struct {
	CreatedOn   openapi_types.Date `json:"created_on"`
	Description *string            `json:"description,omitempty"`
	Id          string             `json:"id"`
	Name        string             `json:"name"`
	UpdatedOn   openapi_types.Date `json:"updated_on"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// CreateOrganizationJSONBody defines parameters for CreateOrganization.
type CreateOrganizationJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// UpdateOrganizationJSONBody defines parameters for UpdateOrganization.
type UpdateOrganizationJSONBody struct {
	Description *string `json:"description,omitempty"`
}

// UpdateProjectJSONBody defines parameters for UpdateProject.
type UpdateProjectJSONBody struct {
	Description *string `json:"description,omitempty"`
}

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody CreateOrganizationJSONBody

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody UpdateOrganizationJSONBody

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody UpdateProjectJSONBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/organizations)
	FindOrganizations(ctx echo.Context) error

	// (POST /v1/organizations)
	CreateOrganization(ctx echo.Context) error

	// (DELETE /v1/organizations/{name})
	DeleteOrganization(ctx echo.Context, name string) error

	// (GET /v1/organizations/{name})
	FindOrganization(ctx echo.Context, name string) error

	// (PUT /v1/organizations/{name})
	UpdateOrganization(ctx echo.Context, name string) error

	// (DELETE /v1/organizations/{organization}/project/{name})
	DeleteProject(ctx echo.Context, organization string, name string) error

	// (GET /v1/organizations/{organization}/project/{name})
	FindProject(ctx echo.Context, organization string, name string) error

	// (PUT /v1/organizations/{organization}/project/{name})
	UpdateProject(ctx echo.Context, organization string, name string) error

	// (GET /v1/organizations/{organization}/projects)
	FindProjects(ctx echo.Context, organization string) error

	// (POST /v1/organizations/{organization}/projects)
	CreateProject(ctx echo.Context, organization string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// FindOrganizations converts echo context to params.
func (w *ServerInterfaceWrapper) FindOrganizations(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindOrganizations(ctx)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteOrganization(ctx, name)
	return err
}

// FindOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) FindOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindOrganization(ctx, name)
	return err
}

// UpdateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateOrganization(ctx, name)
	return err
}

// DeleteProject converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organization" -------------
	var organization string

	err = runtime.BindStyledParameterWithLocation("simple", false, "organization", runtime.ParamLocationPath, ctx.Param("organization"), &organization)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organization: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteProject(ctx, organization, name)
	return err
}

// FindProject converts echo context to params.
func (w *ServerInterfaceWrapper) FindProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organization" -------------
	var organization string

	err = runtime.BindStyledParameterWithLocation("simple", false, "organization", runtime.ParamLocationPath, ctx.Param("organization"), &organization)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organization: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindProject(ctx, organization, name)
	return err
}

// UpdateProject converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organization" -------------
	var organization string

	err = runtime.BindStyledParameterWithLocation("simple", false, "organization", runtime.ParamLocationPath, ctx.Param("organization"), &organization)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organization: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateProject(ctx, organization, name)
	return err
}

// FindProjects converts echo context to params.
func (w *ServerInterfaceWrapper) FindProjects(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organization" -------------
	var organization string

	err = runtime.BindStyledParameterWithLocation("simple", false, "organization", runtime.ParamLocationPath, ctx.Param("organization"), &organization)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organization: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindProjects(ctx, organization)
	return err
}

// CreateProject converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organization" -------------
	var organization string

	err = runtime.BindStyledParameterWithLocation("simple", false, "organization", runtime.ParamLocationPath, ctx.Param("organization"), &organization)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organization: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateProject(ctx, organization)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/organizations", wrapper.FindOrganizations)
	router.POST(baseURL+"/v1/organizations", wrapper.CreateOrganization)
	router.DELETE(baseURL+"/v1/organizations/:name", wrapper.DeleteOrganization)
	router.GET(baseURL+"/v1/organizations/:name", wrapper.FindOrganization)
	router.PUT(baseURL+"/v1/organizations/:name", wrapper.UpdateOrganization)
	router.DELETE(baseURL+"/v1/organizations/:organization/project/:name", wrapper.DeleteProject)
	router.GET(baseURL+"/v1/organizations/:organization/project/:name", wrapper.FindProject)
	router.PUT(baseURL+"/v1/organizations/:organization/project/:name", wrapper.UpdateProject)
	router.GET(baseURL+"/v1/organizations/:organization/projects", wrapper.FindProjects)
	router.POST(baseURL+"/v1/organizations/:organization/projects", wrapper.CreateProject)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQW/bPAz9Kx/47WjUaXvzbetWYLu06DbsUASDajGJClvSKLpAFvi/D5LiOE7c1UWa",
	"YCnqk0TKFPn4HqEF5Ka0RqNmB9kCCJ012mHYfCIydLO0eENuNKNmvxTWFioXrIxO753R3ubyGZbCr94R",
	"TiCD/9M2ehq9Lg1RofZfsvylvc0vLBmLxComkRsZ7p4YKgVDBkrz+RkkwHOLcYtTJKgTKNE5MQ2nl07H",
	"pPQU/E2EvypFKCG7jTHb8+NVMHN3jzn7WFc0FVr9DgX2JEUoGOXP6FulJgVjm1lzeQISXU7KNrG2/Er2",
	"mrUosddRWTn8+o3alYRl5GS9jE7QPkCuyYTlGxaetphXpHj+1dM3wnCHgpDeVzxrd5dNNl9+fIMl2X2k",
	"6G3TmzFbCHpQemJCmYoL77lRRfHfRWEqn+kDkguwwenJ6GTkqzcWtbAKMjgPpgSs4FlIKH04Tc0ai4Nx",
	"iqGDvn/B+FlCBpdKy6vOyaQ7CM5Go2fJXzGW7qk50FFYvcJCEIk5xOkgcSKqgh+LtMox7U6q8K81rqfU",
	"i9DlztWREuj4g5HzZ5XZ1cFTxH6EwRuUDKd6ONc5xlRhvWOPhrdmx1bUyTYV04Wvs46wFci43amPwb7R",
	"KStIlMhIDrLbBSivBU/4RsZZo+YuVsla3Zvwj3tx3JF8g2R2yHr+QV4kYKselL6H0XsgnPav+/r1S3l9",
	"W6c2vhMGK7x5Vwxpstme28OanRzjrDh+ZF6Gwg0Oex04Rwf26x9dL9X3Z0ytv7+Rr5tDeyXJ+BCP7xW2",
	"B313H0Rk47cH/f6kVNd/AgAA//9nMzaDMhIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
