<script lang="ts">
  import { goto } from "$app/navigation";
  import Button from "@rilldata/web-common/components/button/Button.svelte";
  import Dialog from "@rilldata/web-common/components/dialog-v2/Dialog.svelte";
  import { useCreateDashboardFromSourceUIAction } from "@rilldata/web-common/features/sources/createDashboard";
  import { sourceImportedName } from "@rilldata/web-common/features/sources/sources-store";
  import { runtime } from "@rilldata/web-common/runtime-client/runtime-store";

  export let open: boolean;

  $: dashboardFromSourceUIAction = useCreateDashboardFromSourceUIAction(
    $runtime.instanceId,
    $sourceImportedName
  );

  function close() {
    sourceImportedName.set(null);
  }

  function goToSource() {
    goto(`/source/${$sourceImportedName}`);
    close();
  }

  async function autoGenerateDashboard() {
    await dashboardFromSourceUIAction();
    close();
  }
</script>

<Dialog on:close={close} {open}>
  <svelte:fragment slot="title"
    >Source "{$sourceImportedName}" imported successfully.</svelte:fragment
  >
  <svelte:fragment slot="body">What would you like to do next?</svelte:fragment>
  <svelte:fragment slot="footer">
    <div class="flex gap-x-2">
      <div class="grow" />
      <Button on:click={goToSource} type="secondary">View this source</Button>
      <Button on:click={autoGenerateDashboard} type="primary"
        >Autogenerate Dashboard</Button
      >
    </div>
  </svelte:fragment>
</Dialog>
