<script lang="ts">
  import { goto } from "$app/navigation";
  import Button from "@rilldata/web-common/components/button/Button.svelte";
  import Dialog from "@rilldata/web-common/components/dialog/Dialog.svelte";
  import CheckCircleNew from "@rilldata/web-common/components/icons/CheckCircleNew.svelte";
  import { extractFileName } from "@rilldata/web-common/features/sources/extract-file-name";
  import { sourceImportedName } from "@rilldata/web-common/features/sources/sources-store";
  import { runtime } from "@rilldata/web-common/runtime-client/runtime-store";
  import { BehaviourEventMedium } from "../../../metrics/service/BehaviourEventTypes";
  import { MetricsEventSpace } from "../../../metrics/service/MetricsTypes";
  import { useCreateDashboardFromTableUIAction } from "../../metrics-views/ai-generation/generateMetricsView";

  export let open: boolean;

  $: createDashboardFromTable =
    $sourceImportedName !== null
      ? useCreateDashboardFromTableUIAction(
          $runtime.instanceId,
          $sourceImportedName,
          BehaviourEventMedium.Button,
          MetricsEventSpace.Modal,
        )
      : null;

  function close() {
    sourceImportedName.set(null);
  }

  function goToSource() {
    goto(`/source/${extractFileName($sourceImportedName ?? "")}`);
    close();
  }

  async function autoGenerateDashboard() {
    // This should never happen, because the button is
    // disabled when this is null, but adding this check
    // for type narrowing and just in case.
    if (createDashboardFromTable === null) return;
    close();
    await createDashboardFromTable();
  }
</script>

<Dialog on:close={close} {open}>
  <div class="flex flex-auto gap-x-2.5" slot="title">
    <div class="w-6 m-auto ml-0 mr-0">
      <CheckCircleNew className="fill-primary-500" size="24px" />
    </div>
    <div>Source imported successfully</div>
  </div>
  <div class="flex flex-auto gap-x-2.5" slot="body">
    <div class="w-6" />
    <div class="text-slate-500">
      <span class="font-mono text-slate-800 break-all"
        >{$sourceImportedName}</span
      > has been ingested. What would you like to do next?
    </div>
  </div>
  <div class="flex flex-row-reverse gap-x-2 mt-4" slot="footer">
    <Button
      disabled={createDashboardFromTable === null}
      on:click={autoGenerateDashboard}
      type="primary">Generate dashboard with AI</Button
    >
    <Button on:click={goToSource} type="secondary">View this source</Button>
  </div>
</Dialog>
