/**
 * This file is used to rexport types generated by the proto compiler
 * that end up with mangled names that we don't want in product code.
 *
 */
import {
  DashboardState_LeaderboardSortDirection,
  DashboardState_LeaderboardSortType,
} from "@rilldata/web-common/proto/gen/rill/ui/v1/dashboard_pb";

export { DashboardState_LeaderboardSortDirection as SortDirection };
export { DashboardState_LeaderboardSortType as SortType };
