/**
 * Client-side parser for ephemeral measure expressions.
 *
 * Mirrors the server-side grammar in `runtime/metricsview/measure_expression.go`
 * (which is the authority): references to existing measure names, numeric
 * literals, NULL, unary minus, the binary operators + - * / %, parentheses,
 * and an allowlist of scalar functions. Everything else is rejected.
 *
 * The syntax lives in the nearley grammar `measure-expression.ne` (compiled to
 * `measure-expression.js`, see the npm script `build-measure-expression-grammar`).
 * This module wraps it with the checks that a grammar cannot express well:
 * reserved words, string literals and comments (reported with positions before
 * parsing), and the function allowlist, arities and nesting limit (checked on
 * the parsed tree, mirroring the server's walk).
 *
 * The client parse exists for inline validation (position-aware errors),
 * autocomplete (extracting referenced names) and URL param validation.
 * One deliberate difference: SQL comments are rejected here, while the server
 * strips them; the server never echoes input, so this is only stricter.
 */
import nearley from "nearley";
import grammar from "./measure-expression.js";

// Keep in sync with `measureExpressionFuncs` in runtime/metricsview/measure_expression.go.
// maxArgs of -1 means unbounded.
export const EPHEMERAL_MEASURE_FUNCTIONS: Record<
  string,
  { minArgs: number; maxArgs: number }
> = {
  abs: { minArgs: 1, maxArgs: 1 },
  round: { minArgs: 1, maxArgs: 2 },
  floor: { minArgs: 1, maxArgs: 1 },
  ceil: { minArgs: 1, maxArgs: 1 },
  sqrt: { minArgs: 1, maxArgs: 1 },
  ln: { minArgs: 1, maxArgs: 1 },
  exp: { minArgs: 1, maxArgs: 1 },
  power: { minArgs: 2, maxArgs: 2 },
  coalesce: { minArgs: 2, maxArgs: -1 },
  nullif: { minArgs: 2, maxArgs: 2 },
  greatest: { minArgs: 2, maxArgs: -1 },
  least: { minArgs: 2, maxArgs: -1 },
};

// Keep in sync with the limits in runtime/metricsview/measure_expression.go.
export const MAX_EPHEMERAL_EXPRESSION_LENGTH = 1024;
const MAX_DEPTH = 32;

// SQL words the server-side parser treats as reserved: a measure with one of
// these names must be double-quoted in expressions. Generated by probing the
// server parser (see runtime/metricsview/measure_expression.go).
export const RESERVED_SQL_WORDS = new Set([
  "add",
  "all",
  "alter",
  "analyze",
  "and",
  "array",
  "as",
  "asc",
  "between",
  "bigint",
  "binary",
  "blob",
  "both",
  "by",
  "call",
  "cascade",
  "case",
  "change",
  "char",
  "character",
  "check",
  "collate",
  "column",
  "constraint",
  "continue",
  "convert",
  "create",
  "cross",
  "cume_dist",
  "cursor",
  "database",
  "databases",
  "day_hour",
  "day_microsecond",
  "day_minute",
  "day_second",
  "dec",
  "decimal",
  "default",
  "delayed",
  "delete",
  "dense_rank",
  "desc",
  "describe",
  "distinct",
  "distinctrow",
  "div",
  "double",
  "drop",
  "dual",
  "else",
  "elseif",
  "enclosed",
  "escaped",
  "except",
  "exists",
  "exit",
  "explain",
  "fetch",
  "first_value",
  "float",
  "float4",
  "float8",
  "for",
  "force",
  "foreign",
  "from",
  "fulltext",
  "generated",
  "grant",
  "group",
  "groups",
  "having",
  "high_priority",
  "hour_microsecond",
  "hour_minute",
  "hour_second",
  "if",
  "ignore",
  "ilike",
  "in",
  "index",
  "infile",
  "inner",
  "inout",
  "insert",
  "int",
  "int1",
  "int2",
  "int3",
  "int4",
  "int8",
  "integer",
  "intersect",
  "interval",
  "into",
  "is",
  "iterate",
  "join",
  "key",
  "keys",
  "kill",
  "lag",
  "last_value",
  "lead",
  "leading",
  "leave",
  "left",
  "like",
  "limit",
  "linear",
  "lines",
  "load",
  "lock",
  "long",
  "longblob",
  "longtext",
  "low_priority",
  "match",
  "maxvalue",
  "mediumblob",
  "mediumint",
  "mediumtext",
  "middleint",
  "minute_microsecond",
  "minute_second",
  "mod",
  "natural",
  "no_write_to_binlog",
  "not",
  "nth_value",
  "ntile",
  "numeric",
  "of",
  "on",
  "optimize",
  "option",
  "optionally",
  "or",
  "order",
  "out",
  "outer",
  "outfile",
  "over",
  "partition",
  "percent_rank",
  "precision",
  "primary",
  "procedure",
  "range",
  "rank",
  "read",
  "real",
  "recursive",
  "references",
  "regexp",
  "release",
  "rename",
  "repeat",
  "replace",
  "require",
  "restrict",
  "revoke",
  "right",
  "rlike",
  "row",
  "row_number",
  "rows",
  "schema",
  "schemas",
  "second_microsecond",
  "select",
  "set",
  "show",
  "smallint",
  "spatial",
  "sql",
  "sql_big_result",
  "sql_calc_found_rows",
  "sql_small_result",
  "sqlexception",
  "sqlstate",
  "sqlwarning",
  "ssl",
  "starting",
  "stored",
  "straight_join",
  "table",
  "tablesample",
  "terminated",
  "then",
  "tinyblob",
  "tinyint",
  "tinytext",
  "to",
  "trailing",
  "trigger",
  "union",
  "unique",
  "unlock",
  "unsigned",
  "update",
  "usage",
  "use",
  "using",
  "values",
  "varbinary",
  "varchar",
  "varcharacter",
  "varying",
  "virtual",
  "when",
  "where",
  "while",
  "window",
  "with",
  "write",
  "xor",
  "year_month",
  "zerofill",
]);

// Bare true/false parse as numeric literals server-side, and NULL as the null
// literal; measures with these names must also be quoted.
const LITERAL_WORDS = new Set(["true", "false", "null"]);

/**
 * Formats a measure name for insertion into an expression, double-quoting it
 * when a bare reference would not survive the server-side SQL parser.
 */
export function formatMeasureRef(name: string): string {
  const lower = name.toLowerCase();
  if (
    /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) &&
    !RESERVED_SQL_WORDS.has(lower) &&
    !LITERAL_WORDS.has(lower)
  ) {
    return name;
  }
  return `"${name.replace(/"/g, '""')}"`;
}

export type MeasureExpressionError = {
  message: string;
  // 0-based character offset into the expression where the error was detected.
  position: number;
};

export type MeasureExpressionParseResult = {
  // Referenced identifiers, deduplicated in order of first appearance.
  refs: string[];
  error?: MeasureExpressionError;
};

// Parse tree produced by the grammar's postprocessors.
// `pos` is the 0-based offset of the node's first character.
type Node =
  | { type: "literal"; literal: string; pos: number }
  | { type: "ref"; name: string; pos: number }
  // A bare identifier: a measure reference unless it spells a literal.
  | { type: "word"; name: string; pos: number }
  | { type: "func"; name: string; args: Node[]; pos: number }
  | { type: "paren"; expr: Node; pos: number }
  | { type: "unary"; expr: Node; pos: number }
  | { type: "binary"; op: string; left: Node; right: Node; pos: number };

class ParseError extends Error {
  position: number;
  constructor(message: string, position: number) {
    super(message);
    this.position = position;
  }
}

const compiledGrammar = nearley.Grammar.fromCompiled(grammar);

/**
 * Parses and validates an ephemeral measure expression.
 * Returns the referenced identifiers, or a position-aware error.
 * Note this validates the grammar only; callers must separately check that
 * each ref is an existing measure name.
 */
export function parseMeasureExpression(
  expression: string,
): MeasureExpressionParseResult {
  if (expression.trim() === "") {
    return { refs: [], error: { message: "expression is empty", position: 0 } };
  }
  if (expression.length > MAX_EPHEMERAL_EXPRESSION_LENGTH) {
    return {
      refs: [],
      error: {
        message: `expression exceeds the maximum length of ${MAX_EPHEMERAL_EXPRESSION_LENGTH} characters`,
        position: MAX_EPHEMERAL_EXPRESSION_LENGTH,
      },
    };
  }
  try {
    const refs: string[] = [];
    walk(parse(expression), 0, refs);
    if (refs.length === 0) {
      return {
        refs: [],
        error: {
          message: "expression must reference at least one measure",
          position: 0,
        },
      };
    }
    return { refs };
  } catch (e) {
    if (e instanceof ParseError) {
      return { refs: [], error: { message: e.message, position: e.position } };
    }
    throw e;
  }
}

/**
 * Runs the grammar and turns its failures into position-aware errors.
 * Lexical problems the grammar only reports as a generic syntax error (reserved
 * words, string literals, comments, malformed quoted identifiers) are found by a
 * pre-scan; whichever error comes first in the input wins, so errors are always
 * reported left to right.
 */
function parse(expression: string): Node {
  const lexical = scanLexicalErrors(expression);
  const parser = new nearley.Parser(compiledGrammar);
  try {
    parser.feed(expression);
  } catch (e) {
    const offset = (e as { offset?: number }).offset ?? 0;
    if (lexical && lexical.position <= offset) throw lexical;
    throw syntaxError(expression, offset);
  }
  if (lexical) throw lexical;
  const root = parser.results[0] as Node | undefined;
  if (!root) {
    // The input is a valid prefix of an expression but ends too early.
    const partial = partialNumberError(expression, expression.length);
    if (partial) throw partial;
    const opens = (expression.match(/\(/g) ?? []).length;
    const closes = (expression.match(/\)/g) ?? []).length;
    throw new ParseError(
      opens > closes
        ? "expected closing parenthesis"
        : "unexpected end of expression",
      expression.length,
    );
  }
  return root;
}

/**
 * Scans the raw input for constructs the server rejects or interprets
 * differently, which the grammar cannot describe with a useful message.
 * Returns the first one found, if any.
 */
function scanLexicalErrors(input: string): ParseError | undefined {
  let i = 0;
  while (i < input.length) {
    const ch = input[i];
    if (ch === '"') {
      const start = i;
      let length = 0;
      i++;
      for (;;) {
        if (i >= input.length) {
          return new ParseError("unterminated quoted identifier", start);
        }
        if (input[i] === '"') {
          if (input[i + 1] !== '"') break;
          i++;
        }
        length++;
        i++;
      }
      i++;
      if (length === 0) return new ParseError("empty quoted identifier", start);
      continue;
    }
    if (ch === "'") {
      return new ParseError(
        "string literals are not allowed in the expression",
        i,
      );
    }
    if (ch === "-" && input[i + 1] === "-") {
      // The server-side SQL parser treats `--` as a comment start.
      return new ParseError(
        `comments are not allowed in the expression (found "--"); use parentheses for double negation, e.g. "a - (-b)"`,
        i,
      );
    }
    if (/[A-Za-z_]/.test(ch)) {
      const start = i;
      while (i < input.length && /[A-Za-z0-9_]/.test(input[i])) i++;
      const word = input.slice(start, i);
      if (RESERVED_SQL_WORDS.has(word.toLowerCase())) {
        return new ParseError(
          `"${word}" is a reserved SQL word; wrap it in double quotes to reference a measure with this name`,
          start,
        );
      }
      continue;
    }
    i++;
  }
  return undefined;
}

/**
 * Describes the token at `offset` that the grammar could not accept.
 */
function syntaxError(input: string, offset: number): ParseError {
  const partial = partialNumberError(input, offset);
  if (partial) return partial;
  if (offset >= input.length) {
    return new ParseError("unexpected end of expression", offset);
  }
  const rest = input.slice(offset);
  const token =
    /^[A-Za-z_][A-Za-z0-9_]*/.exec(rest)?.[0] ??
    /^(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?/.exec(rest)?.[0] ??
    /^"(?:[^"]|"")*"/.exec(rest)?.[0].slice(1, -1).replace(/""/g, '"') ??
    (/^[-+*/%(),]/.test(rest) ? rest[0] : undefined);
  if (token === undefined) {
    return new ParseError(`unexpected character "${rest[0]}"`, offset);
  }
  return new ParseError(`unexpected "${token}"`, offset);
}

/**
 * The grammar consumes the "e" (and sign) of an exponent before knowing whether
 * digits follow, so a failure right after one is really a malformed number,
 * e.g. "1e" or "2.5e+"; report it at the start of the number.
 */
function partialNumberError(
  input: string,
  offset: number,
): ParseError | undefined {
  const match = /(?:\d+\.?\d*|\.\d+)[eE][+-]?$/.exec(input.slice(0, offset));
  if (!match) return undefined;
  return new ParseError(`invalid number "${match[0]}"`, match.index);
}

/**
 * Validates the parsed tree and collects referenced measure names, in order of
 * first appearance. Mirrors the server's `parseNode`: every node, including
 * parentheses, counts one level toward the nesting limit, so a flat chain of
 * binary operators is bounded as well as deep nesting.
 */
function walk(node: Node, depth: number, refs: string[]): void {
  if (depth > MAX_DEPTH) {
    throw new ParseError("expression is too deeply nested", node.pos);
  }
  switch (node.type) {
    case "literal":
      return;
    case "ref":
      addRef(refs, node.name);
      return;
    case "word":
      // Bare true/false/null parse as literals server-side.
      if (!LITERAL_WORDS.has(node.name.toLowerCase())) addRef(refs, node.name);
      return;
    case "func": {
      const spec = EPHEMERAL_MEASURE_FUNCTIONS[node.name.toLowerCase()];
      if (!spec) {
        throw new ParseError(`unsupported function "${node.name}"`, node.pos);
      }
      const argCount = node.args.length;
      if (
        argCount < spec.minArgs ||
        (spec.maxArgs >= 0 && argCount > spec.maxArgs)
      ) {
        throw new ParseError(
          `function "${node.name}" does not accept ${argCount} argument(s)`,
          node.pos,
        );
      }
      for (const arg of node.args) walk(arg, depth + 1, refs);
      return;
    }
    case "paren":
    case "unary":
      walk(node.expr, depth + 1, refs);
      return;
    case "binary":
      walk(node.left, depth + 1, refs);
      walk(node.right, depth + 1, refs);
      return;
  }
}

function addRef(refs: string[], name: string): void {
  if (!refs.includes(name)) refs.push(name);
}
