/**
 * Client-side parser for ephemeral measure expressions.
 *
 * Mirrors the server-side grammar in `runtime/metricsview/measure_expression.go`
 * (which is the authority): references to existing measure names, numeric
 * literals, NULL, unary minus, the binary operators + - * / %, parentheses,
 * and an allowlist of scalar functions. Everything else is rejected.
 *
 * The client parse exists for inline validation (position-aware errors),
 * autocomplete (extracting referenced names) and URL param validation.
 * One deliberate difference: SQL comments are rejected here, while the server
 * strips them; the server never echoes input, so this is only stricter.
 */

// Keep in sync with `measureExpressionFuncs` in runtime/metricsview/measure_expression.go.
// maxArgs of -1 means unbounded.
export const EPHEMERAL_MEASURE_FUNCTIONS: Record<
  string,
  { minArgs: number; maxArgs: number }
> = {
  abs: { minArgs: 1, maxArgs: 1 },
  round: { minArgs: 1, maxArgs: 2 },
  floor: { minArgs: 1, maxArgs: 1 },
  ceil: { minArgs: 1, maxArgs: 1 },
  sqrt: { minArgs: 1, maxArgs: 1 },
  ln: { minArgs: 1, maxArgs: 1 },
  exp: { minArgs: 1, maxArgs: 1 },
  power: { minArgs: 2, maxArgs: 2 },
  coalesce: { minArgs: 2, maxArgs: -1 },
  nullif: { minArgs: 2, maxArgs: 2 },
  greatest: { minArgs: 2, maxArgs: -1 },
  least: { minArgs: 2, maxArgs: -1 },
};

// Keep in sync with the limits in runtime/metricsview/measure_expression.go.
export const MAX_EPHEMERAL_EXPRESSION_LENGTH = 1024;
const MAX_DEPTH = 32;

// SQL words the server-side parser treats as reserved: a measure with one of
// these names must be double-quoted in expressions. Generated by probing the
// server parser (see runtime/metricsview/measure_expression.go).
export const RESERVED_SQL_WORDS = new Set([
  "add",
  "all",
  "alter",
  "analyze",
  "and",
  "array",
  "as",
  "asc",
  "between",
  "bigint",
  "binary",
  "blob",
  "both",
  "by",
  "call",
  "cascade",
  "case",
  "change",
  "char",
  "character",
  "check",
  "collate",
  "column",
  "constraint",
  "continue",
  "convert",
  "create",
  "cross",
  "cume_dist",
  "cursor",
  "database",
  "databases",
  "day_hour",
  "day_microsecond",
  "day_minute",
  "day_second",
  "dec",
  "decimal",
  "default",
  "delayed",
  "delete",
  "dense_rank",
  "desc",
  "describe",
  "distinct",
  "distinctrow",
  "div",
  "double",
  "drop",
  "dual",
  "else",
  "elseif",
  "enclosed",
  "escaped",
  "except",
  "exists",
  "exit",
  "explain",
  "fetch",
  "first_value",
  "float",
  "float4",
  "float8",
  "for",
  "force",
  "foreign",
  "from",
  "fulltext",
  "generated",
  "grant",
  "group",
  "groups",
  "having",
  "high_priority",
  "hour_microsecond",
  "hour_minute",
  "hour_second",
  "if",
  "ignore",
  "ilike",
  "in",
  "index",
  "infile",
  "inner",
  "inout",
  "insert",
  "int",
  "int1",
  "int2",
  "int3",
  "int4",
  "int8",
  "integer",
  "intersect",
  "interval",
  "into",
  "is",
  "iterate",
  "join",
  "key",
  "keys",
  "kill",
  "lag",
  "last_value",
  "lead",
  "leading",
  "leave",
  "left",
  "like",
  "limit",
  "linear",
  "lines",
  "load",
  "lock",
  "long",
  "longblob",
  "longtext",
  "low_priority",
  "match",
  "maxvalue",
  "mediumblob",
  "mediumint",
  "mediumtext",
  "middleint",
  "minute_microsecond",
  "minute_second",
  "mod",
  "natural",
  "no_write_to_binlog",
  "not",
  "nth_value",
  "ntile",
  "numeric",
  "of",
  "on",
  "optimize",
  "option",
  "optionally",
  "or",
  "order",
  "out",
  "outer",
  "outfile",
  "over",
  "partition",
  "percent_rank",
  "precision",
  "primary",
  "procedure",
  "range",
  "rank",
  "read",
  "real",
  "recursive",
  "references",
  "regexp",
  "release",
  "rename",
  "repeat",
  "replace",
  "require",
  "restrict",
  "revoke",
  "right",
  "rlike",
  "row",
  "row_number",
  "rows",
  "schema",
  "schemas",
  "second_microsecond",
  "select",
  "set",
  "show",
  "smallint",
  "spatial",
  "sql",
  "sql_big_result",
  "sql_calc_found_rows",
  "sql_small_result",
  "sqlexception",
  "sqlstate",
  "sqlwarning",
  "ssl",
  "starting",
  "stored",
  "straight_join",
  "table",
  "tablesample",
  "terminated",
  "then",
  "tinyblob",
  "tinyint",
  "tinytext",
  "to",
  "trailing",
  "trigger",
  "union",
  "unique",
  "unlock",
  "unsigned",
  "update",
  "usage",
  "use",
  "using",
  "values",
  "varbinary",
  "varchar",
  "varcharacter",
  "varying",
  "virtual",
  "when",
  "where",
  "while",
  "window",
  "with",
  "write",
  "xor",
  "year_month",
  "zerofill",
]);

// Bare true/false parse as numeric literals server-side, and NULL as the null
// literal; measures with these names must also be quoted.
const LITERAL_WORDS = new Set(["true", "false", "null"]);

/**
 * Formats a measure name for insertion into an expression, double-quoting it
 * when a bare reference would not survive the server-side SQL parser.
 */
export function formatMeasureRef(name: string): string {
  const lower = name.toLowerCase();
  if (
    /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) &&
    !RESERVED_SQL_WORDS.has(lower) &&
    !LITERAL_WORDS.has(lower)
  ) {
    return name;
  }
  return `"${name.replace(/"/g, '""')}"`;
}

export type MeasureExpressionError = {
  message: string;
  // 0-based character offset into the expression where the error was detected.
  position: number;
};

export type MeasureExpressionParseResult = {
  // Referenced identifiers, deduplicated in order of first appearance.
  refs: string[];
  error?: MeasureExpressionError;
};

type Token = {
  kind:
    | "ident"
    | "quoted-ident"
    | "number"
    | "op"
    | "lparen"
    | "rparen"
    | "comma"
    | "null"
    | "eof";
  text: string;
  pos: number;
};

const IDENT_START = /[A-Za-z_]/;
const IDENT_CHAR = /[A-Za-z0-9_]/;

class ParseError extends Error {
  position: number;
  constructor(message: string, position: number) {
    super(message);
    this.position = position;
  }
}

function tokenize(input: string): Token[] {
  const tokens: Token[] = [];
  let i = 0;
  while (i < input.length) {
    const ch = input[i];
    if (ch === " " || ch === "\t" || ch === "\n" || ch === "\r") {
      i++;
      continue;
    }
    if (ch === "(") {
      tokens.push({ kind: "lparen", text: ch, pos: i });
      i++;
      continue;
    }
    if (ch === ")") {
      tokens.push({ kind: "rparen", text: ch, pos: i });
      i++;
      continue;
    }
    if (ch === ",") {
      tokens.push({ kind: "comma", text: ch, pos: i });
      i++;
      continue;
    }
    if (ch === "-" && input[i + 1] === "-") {
      // The server-side SQL parser treats `--` as a comment start.
      throw new ParseError(
        `comments are not allowed in the expression (found "--"); use parentheses for double negation, e.g. "a - (-b)"`,
        i,
      );
    }
    if ("+-*/%".includes(ch)) {
      tokens.push({ kind: "op", text: ch, pos: i });
      i++;
      continue;
    }
    if (ch === '"') {
      // Double-quoted identifier; "" escapes a quote, matching ANSI SQL.
      const start = i;
      i++;
      let name = "";
      let closed = false;
      while (i < input.length) {
        if (input[i] === '"') {
          if (input[i + 1] === '"') {
            name += '"';
            i += 2;
            continue;
          }
          closed = true;
          i++;
          break;
        }
        name += input[i];
        i++;
      }
      if (!closed) {
        throw new ParseError("unterminated quoted identifier", start);
      }
      if (name === "") {
        throw new ParseError("empty quoted identifier", start);
      }
      tokens.push({ kind: "quoted-ident", text: name, pos: start });
      continue;
    }
    if (ch === "'") {
      throw new ParseError(
        "string literals are not allowed in the expression",
        i,
      );
    }
    if (/[0-9]/.test(ch) || (ch === "." && /[0-9]/.test(input[i + 1] ?? ""))) {
      const start = i;
      const match = /^(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?/.exec(
        input.slice(i),
      );
      if (!match) {
        throw new ParseError(`invalid number`, start);
      }
      tokens.push({ kind: "number", text: match[0], pos: start });
      i += match[0].length;
      continue;
    }
    if (IDENT_START.test(ch)) {
      const start = i;
      let name = "";
      while (i < input.length && IDENT_CHAR.test(input[i])) {
        name += input[i];
        i++;
      }
      const lower = name.toLowerCase();
      if (LITERAL_WORDS.has(lower)) {
        // Parsed as literals by the server-side SQL parser.
        tokens.push({ kind: "null", text: name, pos: start });
      } else if (RESERVED_SQL_WORDS.has(lower)) {
        throw new ParseError(
          `"${name}" is a reserved SQL word; wrap it in double quotes to reference a measure with this name`,
          start,
        );
      } else {
        tokens.push({ kind: "ident", text: name, pos: start });
      }
      continue;
    }
    throw new ParseError(`unexpected character "${ch}"`, i);
  }
  tokens.push({ kind: "eof", text: "", pos: input.length });
  return tokens;
}

class Parser {
  private tokens: Token[];
  private index = 0;
  private complexity = 0;
  refs: string[] = [];

  constructor(tokens: Token[]) {
    this.tokens = tokens;
  }

  // The server parser builds a left-nested tree, so every binary operator adds
  // a nesting level toward its depth limit; mirror that with a combined budget.
  private spendComplexity(pos: number): void {
    this.complexity++;
    if (this.complexity > MAX_DEPTH) {
      throw new ParseError("expression is too deeply nested", pos);
    }
  }

  private peek(): Token {
    return this.tokens[this.index];
  }

  private next(): Token {
    return this.tokens[this.index++];
  }

  parse(): void {
    this.parseAdditive(0);
    const tok = this.peek();
    if (tok.kind !== "eof") {
      throw new ParseError(`unexpected "${tok.text}"`, tok.pos);
    }
  }

  private parseAdditive(depth: number): void {
    this.parseMultiplicative(depth);
    while (this.peek().kind === "op" && "+-".includes(this.peek().text)) {
      this.spendComplexity(this.next().pos);
      this.parseMultiplicative(depth);
    }
  }

  private parseMultiplicative(depth: number): void {
    this.parseUnary(depth);
    while (this.peek().kind === "op" && "*/%".includes(this.peek().text)) {
      this.spendComplexity(this.next().pos);
      this.parseUnary(depth);
    }
  }

  private parseUnary(depth: number): void {
    if (depth > MAX_DEPTH) {
      throw new ParseError("expression is too deeply nested", this.peek().pos);
    }
    if (this.peek().kind === "op" && this.peek().text === "-") {
      this.spendComplexity(this.peek().pos);
      this.next();
      this.parseUnary(depth + 1);
      return;
    }
    this.parsePrimary(depth);
  }

  private parsePrimary(depth: number): void {
    const tok = this.next();
    switch (tok.kind) {
      case "number":
      case "null":
        return;
      case "quoted-ident":
        this.addRef(tok.text);
        return;
      case "ident": {
        if (this.peek().kind === "lparen") {
          this.parseFunctionCall(tok, depth);
          return;
        }
        this.addRef(tok.text);
        return;
      }
      case "lparen": {
        this.parseAdditive(depth + 1);
        const close = this.next();
        if (close.kind !== "rparen") {
          throw new ParseError("expected closing parenthesis", close.pos);
        }
        return;
      }
      case "eof":
        throw new ParseError("unexpected end of expression", tok.pos);
      default:
        throw new ParseError(`unexpected "${tok.text}"`, tok.pos);
    }
  }

  private parseFunctionCall(nameTok: Token, depth: number): void {
    const fnName = nameTok.text.toLowerCase();
    const spec = EPHEMERAL_MEASURE_FUNCTIONS[fnName];
    if (!spec) {
      throw new ParseError(
        `unsupported function "${nameTok.text}"`,
        nameTok.pos,
      );
    }
    this.next(); // consume the lparen
    let argCount = 0;
    if (this.peek().kind !== "rparen") {
      for (;;) {
        this.parseAdditive(depth + 1);
        argCount++;
        if (this.peek().kind === "comma") {
          this.next();
          continue;
        }
        break;
      }
    }
    const close = this.next();
    if (close.kind !== "rparen") {
      throw new ParseError("expected closing parenthesis", close.pos);
    }
    if (
      argCount < spec.minArgs ||
      (spec.maxArgs >= 0 && argCount > spec.maxArgs)
    ) {
      throw new ParseError(
        `function "${nameTok.text}" does not accept ${argCount} argument(s)`,
        nameTok.pos,
      );
    }
  }

  private addRef(name: string): void {
    if (!this.refs.includes(name)) {
      this.refs.push(name);
    }
  }
}

/**
 * Parses and validates an ephemeral measure expression.
 * Returns the referenced identifiers, or a position-aware error.
 * Note this validates the grammar only; callers must separately check that
 * each ref is an existing measure name.
 */
export function parseMeasureExpression(
  expression: string,
): MeasureExpressionParseResult {
  if (expression.trim() === "") {
    return { refs: [], error: { message: "expression is empty", position: 0 } };
  }
  if (expression.length > MAX_EPHEMERAL_EXPRESSION_LENGTH) {
    return {
      refs: [],
      error: {
        message: `expression exceeds the maximum length of ${MAX_EPHEMERAL_EXPRESSION_LENGTH} characters`,
        position: MAX_EPHEMERAL_EXPRESSION_LENGTH,
      },
    };
  }
  try {
    const parser = new Parser(tokenize(expression));
    parser.parse();
    if (parser.refs.length === 0) {
      return {
        refs: [],
        error: {
          message: "expression must reference at least one measure",
          position: 0,
        },
      };
    }
    return { refs: parser.refs };
  } catch (e) {
    if (e instanceof ParseError) {
      return { refs: [], error: { message: e.message, position: e.position } };
    }
    throw e;
  }
}
