name: Claude on comment

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run-claude:
    if: (github.event.issue.pull_request || github.event.pull_request) &&
        contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug trigger
        run: |
          echo "Triggered by: ${{ github.event.comment.body }}"
          echo "PR #:   ${{ github.event.issue.number }}"

      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Review all inline and general PR comments for PR #${{ github.event.issue.number || github.event.pull_request.number }}.
            Make safe, unambiguous edits (typos, doc fixes, small refactors) that clearly address reviewer feedback.
            Commit and push to this PR branch.
