# .github/workflows/claude-comment.yml
name: Claude on comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  run-claude:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: steer behavior so it reads inline comments and applies fixes
          prompt: |
            Review the inline PR comments and discussion for PR #${{ github.event.issue.number }}.
            Make only safe, unambiguous edits (docs, typos, formatting, simple refactors)
            that clearly address reviewers’ feedback. Commit and push to this PR branch.
